/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.agent;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.touch.models.touch.department.DepartmentNoAgentsResponse;
import io.swagger.annotations.ApiModelProperty;


/**
 * AgentResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T12:15:53.907Z")
public class AgentResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("createdDate")
  private Long createdDate = null;

  @SerializedName("modifiedDate")
  private Long modifiedDate = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("surname")
  private String surname = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("agentJid")
  private String agentJid = null;

  @SerializedName("maxChats")
  private Integer maxChats = null;

  @SerializedName("imageUrl")
  private String imageUrl = null;

  @SerializedName("departments")
  private List<DepartmentNoAgentsResponse> departments = new ArrayList<DepartmentNoAgentsResponse>();

  public AgentResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgentResponse createdDate(Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(Long createdDate) {
    this.createdDate = createdDate;
  }

  public AgentResponse modifiedDate(Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * Get modifiedDate
   * @return modifiedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(Long modifiedDate) {
    this.modifiedDate = modifiedDate;
  }

  public AgentResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public AgentResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AgentResponse surname(String surname) {
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSurname() {
    return surname;
  }

  public void setSurname(String surname) {
    this.surname = surname;
  }

  public AgentResponse email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AgentResponse agentJid(String agentJid) {
    this.agentJid = agentJid;
    return this;
  }

   /**
   * Get agentJid
   * @return agentJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAgentJid() {
    return agentJid;
  }

  public void setAgentJid(String agentJid) {
    this.agentJid = agentJid;
  }

  public AgentResponse maxChats(Integer maxChats) {
    this.maxChats = maxChats;
    return this;
  }

   /**
   * Get maxChats
   * @return maxChats
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMaxChats() {
    return maxChats;
  }

  public void setMaxChats(Integer maxChats) {
    this.maxChats = maxChats;
  }

  public AgentResponse imageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Get imageUrl
   * @return imageUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public AgentResponse departments(List<DepartmentNoAgentsResponse> departments) {
    this.departments = departments;
    return this;
  }

  public AgentResponse addDepartmentsItem(DepartmentNoAgentsResponse departmentsItem) {
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Get departments
   * @return departments
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DepartmentNoAgentsResponse> getDepartments() {
    return departments;
  }

  public void setDepartments(List<DepartmentNoAgentsResponse> departments) {
    this.departments = departments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentResponse agentResponse = (AgentResponse) o;
    return Objects.equals(this.id, agentResponse.id) &&
        Objects.equals(this.createdDate, agentResponse.createdDate) &&
        Objects.equals(this.modifiedDate, agentResponse.modifiedDate) &&
        Objects.equals(this.tenantId, agentResponse.tenantId) &&
        Objects.equals(this.name, agentResponse.name) &&
        Objects.equals(this.surname, agentResponse.surname) &&
        Objects.equals(this.email, agentResponse.email) &&
        Objects.equals(this.agentJid, agentResponse.agentJid) &&
        Objects.equals(this.maxChats, agentResponse.maxChats) &&
        Objects.equals(this.imageUrl, agentResponse.imageUrl) &&
        Objects.equals(this.departments, agentResponse.departments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdDate, modifiedDate, tenantId, name, surname, email, agentJid, maxChats, imageUrl, departments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    agentJid: ").append(toIndentedString(agentJid)).append("\n");
    sb.append("    maxChats: ").append(toIndentedString(maxChats)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

