/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.chats;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * ChatSessionResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-10-20T12:15:53.907Z")
public class ChatSessionResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("startedDate")
  private Long startedDate = null;

  @SerializedName("endedDate")
  private Long endedDate = null;

  @SerializedName("sessionId")
  private String sessionId = null;

  @SerializedName("userMeta")
  private String userMeta = null;

  public ChatSessionResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ChatSessionResponse clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ChatSessionResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public ChatSessionResponse state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public ChatSessionResponse startedDate(Long startedDate) {
    this.startedDate = startedDate;
    return this;
  }

   /**
   * Get startedDate
   * @return startedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getStartedDate() {
    return startedDate;
  }

  public void setStartedDate(Long startedDate) {
    this.startedDate = startedDate;
  }

  public ChatSessionResponse endedDate(Long endedDate) {
    this.endedDate = endedDate;
    return this;
  }

   /**
   * Get endedDate
   * @return endedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEndedDate() {
    return endedDate;
  }

  public void setEndedDate(Long endedDate) {
    this.endedDate = endedDate;
  }

  public ChatSessionResponse sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public ChatSessionResponse userMeta(String userMeta) {
    this.userMeta = userMeta;
    return this;
  }

   /**
   * Get userMeta
   * @return userMeta
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserMeta() {
    return userMeta;
  }

  public void setUserMeta(String userMeta) {
    this.userMeta = userMeta;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatSessionResponse chatSessionResponse = (ChatSessionResponse) o;
    return Objects.equals(this.id, chatSessionResponse.id) &&
        Objects.equals(this.clientId, chatSessionResponse.clientId) &&
        Objects.equals(this.tenantId, chatSessionResponse.tenantId) &&
        Objects.equals(this.state, chatSessionResponse.state) &&
        Objects.equals(this.sessionId, chatSessionResponse.sessionId) &&
        Objects.equals(this.userMeta, chatSessionResponse.userMeta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, clientId, tenantId, state, startedDate, endedDate, sessionId, userMeta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatSessionResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    startedDate: ").append(toIndentedString(startedDate)).append("\n");
    sb.append("    endedDate: ").append(toIndentedString(endedDate)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    userMeta: ").append(toIndentedString(userMeta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

