/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.chats;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.Map;

public class ChatEventResponseV5 {
  @SerializedName("name")
  private String name = null;

  @SerializedName("source")
  private String source = null;

  @SerializedName("tag")
  private String tag = null;

  @SerializedName("descrption")
  private String descrption = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("sessionId")
  private String sessionId = null;

  @SerializedName("fields")
  private Map<String, String> fields = new HashMap<String, String>();

  public ChatEventResponseV5 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ChatEventResponseV5 source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public ChatEventResponseV5 tag(String tag) {
    this.tag = tag;
    return this;
  }

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTag() {
    return tag;
  }

  public void setTag(String tag) {
    this.tag = tag;
  }

  public ChatEventResponseV5 descrption(String descrption) {
    this.descrption = descrption;
    return this;
  }

   /**
   * Get descrption
   * @return descrption
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescrption() {
    return descrption;
  }

  public void setDescrption(String descrption) {
    this.descrption = descrption;
  }

  public ChatEventResponseV5 timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public ChatEventResponseV5 tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public ChatEventResponseV5 clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ChatEventResponseV5 sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }

  public ChatEventResponseV5 fields(Map<String, String> fields) {
    this.fields = fields;
    return this;
  }

  public ChatEventResponseV5 putFieldsItem(String key, String fieldsItem) {
    this.fields.put(key, fieldsItem);
    return this;
  }

   /**
   * Get fields
   * @return fields
  **/
  @ApiModelProperty(example = "null", value = "")
  public Map<String, String> getFields() {
    return fields;
  }

  public void setFields(Map<String, String> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatEventResponseV5 chatEventResponseV5 = (ChatEventResponseV5) o;
    return Objects.equals(this.name, chatEventResponseV5.name) &&
        Objects.equals(this.source, chatEventResponseV5.source) &&
        Objects.equals(this.tag, chatEventResponseV5.tag) &&
        Objects.equals(this.descrption, chatEventResponseV5.descrption) &&
        Objects.equals(this.timestamp, chatEventResponseV5.timestamp) &&
        Objects.equals(this.tenantId, chatEventResponseV5.tenantId) &&
        Objects.equals(this.clientId, chatEventResponseV5.clientId) &&
        Objects.equals(this.sessionId, chatEventResponseV5.sessionId) &&
        Objects.equals(this.fields, chatEventResponseV5.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, source, tag, descrption, timestamp, tenantId, clientId, sessionId, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatEventResponseV5 {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    descrption: ").append(toIndentedString(descrption)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

