/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.chats;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

public class ListChatInviteHistoryArchiveResponse {
  @SerializedName("chatInviteHistory")
  private List<ChatInviteHistoryArchiveResponse> chatInviteHistory = new ArrayList<ChatInviteHistoryArchiveResponse>();

  public ListChatInviteHistoryArchiveResponse chatInviteHistory(List<ChatInviteHistoryArchiveResponse> chatInviteHistory) {
    this.chatInviteHistory = chatInviteHistory;
    return this;
  }

  public ListChatInviteHistoryArchiveResponse addChatInviteHistoryItem(ChatInviteHistoryArchiveResponse chatInviteHistoryItem) {
    this.chatInviteHistory.add(chatInviteHistoryItem);
    return this;
  }

   /**
   * Get chatInviteHistory
   * @return chatInviteHistory
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ChatInviteHistoryArchiveResponse> getChatInviteHistory() {
    return chatInviteHistory;
  }

  public void setChatInviteHistory(List<ChatInviteHistoryArchiveResponse> chatInviteHistory) {
    this.chatInviteHistory = chatInviteHistory;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListChatInviteHistoryArchiveResponse listChatInviteHistoryResponseV5 = (ListChatInviteHistoryArchiveResponse) o;
    return Objects.equals(this.chatInviteHistory, listChatInviteHistoryResponseV5.chatInviteHistory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chatInviteHistory);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListChatInviteHistoryResponseV5 {\n");
    
    sb.append("    chatInviteHistory: ").append(toIndentedString(chatInviteHistory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

