/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * AgentNoDepartmentsResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-06T15:43:34.475Z")
public class AgentNoDepartmentsResponse {

  public AgentNoDepartmentsResponse() {
  }

  public AgentNoDepartmentsResponse(String id, Long createdDate, Long modifiedDate, String tenantJid, String name, String nick, String email, String agentJid, String workPhone, String tenantId, Integer sessionsCapacity) {
    this.id = id;
    this.createdDate = createdDate;
    this.modifiedDate = modifiedDate;
    this.tenantJid = tenantJid;
    this.name = name;
    this.nick = nick;
    this.email = email;
    this.agentJid = agentJid;
    this.workPhone = workPhone;
    this.tenantId = tenantId;
    this.sessionsCapacity = sessionsCapacity;
  }

  @SerializedName("id")
  private String id = null;

  @SerializedName("createdDate")
  private Long createdDate = null;

  @SerializedName("modifiedDate")
  private Long modifiedDate = null;

  @SerializedName("tenantJid")
  private String tenantJid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("nick")
  private String nick = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("agentJid")
  private String agentJid = null;

  @SerializedName("workPhone")
  private String workPhone = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("sessionsCapacity")
  private Integer sessionsCapacity = null;

  public AgentNoDepartmentsResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AgentNoDepartmentsResponse createdDate(Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(Long createdDate) {
    this.createdDate = createdDate;
  }

  public AgentNoDepartmentsResponse modifiedDate(Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * Get modifiedDate
   * @return modifiedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(Long modifiedDate) {
    this.modifiedDate = modifiedDate;
  }

  public AgentNoDepartmentsResponse tenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
    return this;
  }

   /**
   * Get tenantJid
   * @return tenantJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantJid() {
    return tenantJid;
  }

  public void setTenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
  }

  public AgentNoDepartmentsResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AgentNoDepartmentsResponse nick(String nick) {
    this.nick = nick;
    return this;
  }

   /**
   * Get nick
   * @return nick
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNick() {
    return nick;
  }

  public void setNick(String nick) {
    this.nick = nick;
  }

  public AgentNoDepartmentsResponse email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public AgentNoDepartmentsResponse agentJid(String agentJid) {
    this.agentJid = agentJid;
    return this;
  }

   /**
   * Get agentJid
   * @return agentJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAgentJid() {
    return agentJid;
  }

  public void setAgentJid(String agentJid) {
    this.agentJid = agentJid;
  }

  public AgentNoDepartmentsResponse workPhone(String workPhone) {
    this.workPhone = workPhone;
    return this;
  }

   /**
   * Get workPhone
   * @return workPhone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getWorkPhone() {
    return workPhone;
  }

  public void setWorkPhone(String workPhone) {
    this.workPhone = workPhone;
  }

  public AgentNoDepartmentsResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public AgentNoDepartmentsResponse sessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
    return this;
  }

   /**
   * Get sessionsCapacity
   * @return sessionsCapacity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSessionsCapacity() {
    return sessionsCapacity;
  }

  public void setSessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentNoDepartmentsResponse agentNoDepartmentsResponse = (AgentNoDepartmentsResponse) o;
    return Objects.equals(this.id, agentNoDepartmentsResponse.id) &&
        Objects.equals(this.createdDate, agentNoDepartmentsResponse.createdDate) &&
        Objects.equals(this.modifiedDate, agentNoDepartmentsResponse.modifiedDate) &&
        Objects.equals(this.tenantJid, agentNoDepartmentsResponse.tenantJid) &&
        Objects.equals(this.name, agentNoDepartmentsResponse.name) &&
        Objects.equals(this.nick, agentNoDepartmentsResponse.nick) &&
        Objects.equals(this.email, agentNoDepartmentsResponse.email) &&
        Objects.equals(this.agentJid, agentNoDepartmentsResponse.agentJid) &&
        Objects.equals(this.workPhone, agentNoDepartmentsResponse.workPhone) &&
        Objects.equals(this.tenantId, agentNoDepartmentsResponse.tenantId) &&
        Objects.equals(this.sessionsCapacity, agentNoDepartmentsResponse.sessionsCapacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdDate, modifiedDate, tenantJid, name, nick, email, agentJid, workPhone, tenantId, sessionsCapacity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentNoDepartmentsResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    tenantJid: ").append(toIndentedString(tenantJid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nick: ").append(toIndentedString(nick)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    agentJid: ").append(toIndentedString(agentJid)).append("\n");
    sb.append("    workPhone: ").append(toIndentedString(workPhone)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

