/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * TenantResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-06T15:43:34.475Z")
public class TenantResponse extends Tenant{

  public TenantResponse() {
  }

  public TenantResponse(String accountId, String tenantOrgName, String contactEmail, StateEnum state, String description, String shortDescription, String tenantJid, String tenantBotJid, String category, List<String> tenantTags, Integer sessionsCapacity, List<TenantFaqDto> tenantFaqs, List<TenantColourDto> tenantColours, List<AddressResponse> tenantAddresses, String id, List<String> tenantResources, List<DepartmentResponse> departments) {
    this.accountId = accountId;
    this.tenantOrgName = tenantOrgName;
    this.contactEmail = contactEmail;
    this.state = state;
    this.description = description;
    this.shortDescription = shortDescription;
    this.tenantJid = tenantJid;
    this.tenantBotJid = tenantBotJid;
    this.category = category;
    this.tenantTags = tenantTags;
    this.sessionsCapacity = sessionsCapacity;
    this.tenantFaqs = tenantFaqs;
    this.tenantColours = tenantColours;
    this.tenantAddresses = tenantAddresses;
    this.id = id;
    this.tenantResources = tenantResources;
    this.departments = departments;
  }

  @SerializedName("accountId")
  private String accountId = null;


  @SerializedName("tenantFaqs")
  private List<TenantFaqDto> tenantFaqs = new ArrayList<TenantFaqDto>();

  @SerializedName("tenantColours")
  private List<TenantColourDto> tenantColours = new ArrayList<TenantColourDto>();

  @SerializedName("tenantAddresses")
  private List<AddressResponse> tenantAddresses = new ArrayList<AddressResponse>();

  @SerializedName("id")
  private String id = null;

  @SerializedName("tenantResources")
  private List<String> tenantResources = new ArrayList<String>();

  @SerializedName("departments")
  private List<DepartmentResponse> departments = new ArrayList<DepartmentResponse>();

  public TenantResponse accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public TenantResponse tenantOrgName(String tenantOrgName) {
    this.tenantOrgName = tenantOrgName;
    return this;
  }

   /**
   * Get tenantOrgName
   * @return tenantOrgName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantOrgName() {
    return tenantOrgName;
  }

  public void setTenantOrgName(String tenantOrgName) {
    this.tenantOrgName = tenantOrgName;
  }

  public TenantResponse contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * Get contactEmail
   * @return contactEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public TenantResponse state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public TenantResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TenantResponse shortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * Get shortDescription
   * @return shortDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public TenantResponse tenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
    return this;
  }

   /**
   * Get tenantJid
   * @return tenantJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantJid() {
    return tenantJid;
  }

  public void setTenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
  }

  public TenantResponse tenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
    return this;
  }

   /**
   * Get tenantBotJid
   * @return tenantBotJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantBotJid() {
    return tenantBotJid;
  }

  public void setTenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
  }

  public TenantResponse category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public TenantResponse tenantTags(List<String> tenantTags) {
    this.tenantTags = tenantTags;
    return this;
  }

  public TenantResponse addTenantTagsItem(String tenantTagsItem) {
    this.tenantTags.add(tenantTagsItem);
    return this;
  }

   /**
   * Get tenantTags
   * @return tenantTags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTenantTags() {
    return tenantTags;
  }

  public void setTenantTags(List<String> tenantTags) {
    this.tenantTags = tenantTags;
  }

  public TenantResponse sessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
    return this;
  }

   /**
   * Get sessionsCapacity
   * @return sessionsCapacity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSessionsCapacity() {
    return sessionsCapacity;
  }

  public void setSessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
  }

  public TenantResponse tenantFaqs(List<TenantFaqDto> tenantFaqs) {
    this.tenantFaqs = tenantFaqs;
    return this;
  }

  public TenantResponse addTenantFaqsItem(TenantFaqDto tenantFaqsItem) {
    this.tenantFaqs.add(tenantFaqsItem);
    return this;
  }

   /**
   * Get tenantFaqs
   * @return tenantFaqs
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TenantFaqDto> getTenantFaqs() {
    return tenantFaqs;
  }

  public void setTenantFaqs(List<TenantFaqDto> tenantFaqs) {
    this.tenantFaqs = tenantFaqs;
  }

  public TenantResponse tenantColours(List<TenantColourDto> tenantColours) {
    this.tenantColours = tenantColours;
    return this;
  }

  public TenantResponse addTenantColoursItem(TenantColourDto tenantColoursItem) {
    this.tenantColours.add(tenantColoursItem);
    return this;
  }

   /**
   * Get tenantColours
   * @return tenantColours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TenantColourDto> getTenantColours() {
    return tenantColours;
  }

  public void setTenantColours(List<TenantColourDto> tenantColours) {
    this.tenantColours = tenantColours;
  }

  public TenantResponse tenantAddresses(List<AddressResponse> tenantAddresses) {
    this.tenantAddresses = tenantAddresses;
    return this;
  }

  public TenantResponse addTenantAddressesItem(AddressResponse tenantAddressesItem) {
    this.tenantAddresses.add(tenantAddressesItem);
    return this;
  }

   /**
   * Get tenantAddresses
   * @return tenantAddresses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressResponse> getTenantAddresses() {
    return tenantAddresses;
  }

  public void setTenantAddresses(List<AddressResponse> tenantAddresses) {
    this.tenantAddresses = tenantAddresses;
  }

  public TenantResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TenantResponse tenantResources(List<String> tenantResources) {
    this.tenantResources = tenantResources;
    return this;
  }

  public TenantResponse addTenantResourcesItem(String tenantResourcesItem) {
    this.tenantResources.add(tenantResourcesItem);
    return this;
  }

   /**
   * Get tenantResources
   * @return tenantResources
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTenantResources() {
    return tenantResources;
  }

  public void setTenantResources(List<String> tenantResources) {
    this.tenantResources = tenantResources;
  }

  public TenantResponse departments(List<DepartmentResponse> departments) {
    this.departments = departments;
    return this;
  }

  public TenantResponse addDepartmentsItem(DepartmentResponse departmentsItem) {
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Get departments
   * @return departments
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<DepartmentResponse> getDepartments() {
    return departments;
  }

  public void setDepartments(List<DepartmentResponse> departments) {
    this.departments = departments;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || (getClass() != o.getClass() && TenantRequest.class != o.getClass() && TenantUpdateDto.class != o.getClass())) {
      return false;
    }
    Tenant tenantResponse = (Tenant) o;
    return Objects.equals(this.tenantOrgName, tenantResponse.tenantOrgName) &&
        Objects.equals(this.contactEmail, tenantResponse.contactEmail) &&
        Objects.equals(this.state, tenantResponse.state) &&
        Objects.equals(this.description, tenantResponse.description) &&
        Objects.equals(this.shortDescription, tenantResponse.shortDescription) &&
        Objects.equals(this.tenantJid, tenantResponse.tenantJid) &&
        Objects.equals(this.tenantBotJid, tenantResponse.tenantBotJid) &&
        Objects.equals(this.category, tenantResponse.category) &&
        Objects.equals(this.tenantTags, tenantResponse.tenantTags) &&
        Objects.equals(this.sessionsCapacity, tenantResponse.sessionsCapacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, tenantOrgName, contactEmail, state, description, shortDescription, tenantJid, tenantBotJid, category, tenantTags, sessionsCapacity, tenantFaqs, tenantColours, tenantAddresses, id, tenantResources, departments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantResponse {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    tenantOrgName: ").append(toIndentedString(tenantOrgName)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    tenantJid: ").append(toIndentedString(tenantJid)).append("\n");
    sb.append("    tenantBotJid: ").append(toIndentedString(tenantBotJid)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    tenantTags: ").append(toIndentedString(tenantTags)).append("\n");
    sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
    sb.append("    tenantFaqs: ").append(toIndentedString(tenantFaqs)).append("\n");
    sb.append("    tenantColours: ").append(toIndentedString(tenantColours)).append("\n");
    sb.append("    tenantAddresses: ").append(toIndentedString(tenantAddresses)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantResources: ").append(toIndentedString(tenantResources)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

