/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.roster;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RosterResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-06T12:37:26.274Z")
public class RosterResponse {
  @SerializedName("jid")
  private String jid = null;

  @SerializedName("mucDomain")
  private String mucDomain = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("algorithm")
  private String algorithm = null;

  public RosterResponse jid(String jid) {
    this.jid = jid;
    return this;
  }

   /**
   * Get jid
   * @return jid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getJid() {
    return jid;
  }

  public void setJid(String jid) {
    this.jid = jid;
  }

  public RosterResponse mucDomain(String mucDomain) {
    this.mucDomain = mucDomain;
    return this;
  }

   /**
   * Get mucDomain
   * @return mucDomain
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMucDomain() {
    return mucDomain;
  }

  public void setMucDomain(String mucDomain) {
    this.mucDomain = mucDomain;
  }

  public RosterResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RosterResponse algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * Get algorithm
   * @return algorithm
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RosterResponse rosterResponse = (RosterResponse) o;
    return Objects.equals(this.jid, rosterResponse.jid) &&
        Objects.equals(this.mucDomain, rosterResponse.mucDomain) &&
        Objects.equals(this.description, rosterResponse.description) &&
        Objects.equals(this.algorithm, rosterResponse.algorithm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jid, mucDomain, description, algorithm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RosterResponse {\n");
    
    sb.append("    jid: ").append(toIndentedString(jid)).append("\n");
    sb.append("    mucDomain: ").append(toIndentedString(mucDomain)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

