/**
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.mc2.accounts.request.account_profile;

import com.clickatell.models.mc2.accounts.request.billing_info.AddressInfoRequest;
import com.clickatell.models.mc2.accounts.request.billing_info.ContactInfoRequest;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * AccountProfileDetailsRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T14:40:21.649Z")
public class AccountProfileDetailsRequest {
    @SerializedName("companyContact")
    private CompanyContactInfoRequest companyContact = new CompanyContactInfoRequest();

    @SerializedName("companyAddress")
    private AddressInfoRequest companyAddress = new AddressInfoRequest();

    @SerializedName("adminContact")
    private ContactInfoRequest adminContact = new ContactInfoRequest();

    @SerializedName("adminAddress")
    private AddressInfoRequest adminAddress = new AddressInfoRequest();

    @SerializedName("adminAsSupportReused")
    private Boolean adminAsSupportReused = false;

    @SerializedName("supportContact")
    private ContactInfoRequest supportContact = new ContactInfoRequest();

    @SerializedName("adminAsTechReused")
    private Boolean adminAsTechReused = false;

    @SerializedName("techContact")
    private ContactInfoRequest techContact = new ContactInfoRequest();

    public AccountProfileDetailsRequest companyContact(CompanyContactInfoRequest companyContact) {
        this.companyContact = companyContact;
        return this;
    }

    public AccountProfileDetailsRequest() {
    }

    public AccountProfileDetailsRequest(Integer countryId){
        companyAddress = new AddressInfoRequest(countryId);
        adminAddress = new AddressInfoRequest(countryId);
    }



    /**
     * Company contact
     * @return companyContact
     **/
    @ApiModelProperty(example = "null", value = "Company contact")
    public CompanyContactInfoRequest getCompanyContact() {
        return companyContact;
    }

    public void setCompanyContact(CompanyContactInfoRequest companyContact) {
        this.companyContact = companyContact;
    }

    public AccountProfileDetailsRequest companyAddress(AddressInfoRequest companyAddress) {
        this.companyAddress = companyAddress;
        return this;
    }

    /**
     * Company address
     * @return companyAddress
     **/
    @ApiModelProperty(example = "null", value = "Company address")
    public AddressInfoRequest getCompanyAddress() {
        return companyAddress;
    }

    public void setCompanyAddress(AddressInfoRequest companyAddress) {
        this.companyAddress = companyAddress;
    }

    public AccountProfileDetailsRequest adminContact(ContactInfoRequest adminContact) {
        this.adminContact = adminContact;
        return this;
    }

    /**
     * Admin contact.
     * @return adminContact
     **/
    @ApiModelProperty(example = "null", value = "Admin contact.")
    public ContactInfoRequest getAdminContact() {
        return adminContact;
    }

    public void setAdminContact(ContactInfoRequest adminContact) {
        this.adminContact = adminContact;
    }

    public AccountProfileDetailsRequest adminAddress(AddressInfoRequest adminAddress) {
        this.adminAddress = adminAddress;
        return this;
    }

    /**
     * Admin address
     * @return adminAddress
     **/
    @ApiModelProperty(example = "null", value = "Admin address")
    public AddressInfoRequest getAdminAddress() {
        return adminAddress;
    }

    public void setAdminAddress(AddressInfoRequest adminAddress) {
        this.adminAddress = adminAddress;
    }

    public AccountProfileDetailsRequest adminAsSupportReused(Boolean adminAsSupportReused) {
        this.adminAsSupportReused = adminAsSupportReused;
        return this;
    }

    /**
     * Define if admin contact may be reused as support; false (disabled) by default.
     * @return adminAsSupportReused
     **/
    @ApiModelProperty(example = "null", value = "Define if admin contact may be reused as support; false (disabled) by default.")
    public Boolean getAdminAsSupportReused() {
        return adminAsSupportReused;
    }

    public void setAdminAsSupportReused(Boolean adminAsSupportReused) {
        this.adminAsSupportReused = adminAsSupportReused;
    }

    public AccountProfileDetailsRequest supportContact(ContactInfoRequest supportContact) {
        this.supportContact = supportContact;
        return this;
    }

    /**
     * Support contact.
     * @return supportContact
     **/
    @ApiModelProperty(example = "null", value = "Support contact.")
    public ContactInfoRequest getSupportContact() {
        return supportContact;
    }

    public void setSupportContact(ContactInfoRequest supportContact) {
        this.supportContact = supportContact;
    }

    public AccountProfileDetailsRequest adminAsTechReused(Boolean adminAsTechReused) {
        this.adminAsTechReused = adminAsTechReused;
        return this;
    }

    /**
     * Define if admin contact may be reused as tech; false (disabled) by default.
     * @return adminAsTechReused
     **/
    @ApiModelProperty(example = "null", value = "Define if admin contact may be reused as tech; false (disabled) by default.")
    public Boolean getAdminAsTechReused() {
        return adminAsTechReused;
    }

    public void setAdminAsTechReused(Boolean adminAsTechReused) {
        this.adminAsTechReused = adminAsTechReused;
    }

    public AccountProfileDetailsRequest techContact(ContactInfoRequest techContact) {
        this.techContact = techContact;
        return this;
    }

    /**
     * Tech contact.
     * @return techContact
     **/
    @ApiModelProperty(example = "null", value = "Tech contact.")
    public ContactInfoRequest getTechContact() {
        return techContact;
    }

    public void setTechContact(ContactInfoRequest techContact) {
        this.techContact = techContact;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountProfileDetailsRequest accountProfileDetailsRequest = (AccountProfileDetailsRequest) o;
        return Objects.equals(this.companyContact, accountProfileDetailsRequest.companyContact) &&
                Objects.equals(this.companyAddress, accountProfileDetailsRequest.companyAddress) &&
                Objects.equals(this.adminContact, accountProfileDetailsRequest.adminContact) &&
                Objects.equals(this.adminAddress, accountProfileDetailsRequest.adminAddress) &&
                Objects.equals(this.adminAsSupportReused, accountProfileDetailsRequest.adminAsSupportReused) &&
                Objects.equals(this.supportContact, accountProfileDetailsRequest.supportContact) &&
                Objects.equals(this.adminAsTechReused, accountProfileDetailsRequest.adminAsTechReused) &&
                Objects.equals(this.techContact, accountProfileDetailsRequest.techContact);
    }

    @Override
    public int hashCode() {
        return Objects.hash(companyContact, companyAddress, adminContact, adminAddress, adminAsSupportReused, supportContact, adminAsTechReused, techContact);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccountProfileDetailsRequest {\n");

        sb.append("    companyContact: ").append(toIndentedString(companyContact)).append("\n");
        sb.append("    companyAddress: ").append(toIndentedString(companyAddress)).append("\n");
        sb.append("    adminContact: ").append(toIndentedString(adminContact)).append("\n");
        sb.append("    adminAddress: ").append(toIndentedString(adminAddress)).append("\n");
        sb.append("    adminAsSupportReused: ").append(toIndentedString(adminAsSupportReused)).append("\n");
        sb.append("    supportContact: ").append(toIndentedString(supportContact)).append("\n");
        sb.append("    adminAsTechReused: ").append(toIndentedString(adminAsTechReused)).append("\n");
        sb.append("    techContact: ").append(toIndentedString(techContact)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

