/**
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.mc2.accounts.request.account_profile;

import com.clickatell.utils.StringUtils;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * AccountProfileRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T14:40:21.649Z")
public class AccountProfileRequest {
    @SerializedName("companyName")
    private String companyName = "CompanyName_" + StringUtils.generateRandomString(10);

    @SerializedName("accountTypeId")
    private Integer accountTypeId = null;

    @SerializedName("profileDetails")
    private AccountProfileDetailsRequest profileDetails = new AccountProfileDetailsRequest();


    public AccountProfileRequest(Integer accountTypeId) {
        this.companyName = companyName;
        this.accountTypeId = accountTypeId;
    }

    public AccountProfileRequest(Integer accountTypeId, Integer countryId) {
        this.companyName = companyName;
        this.accountTypeId = accountTypeId;
        profileDetails = new AccountProfileDetailsRequest(countryId);
    }

    public AccountProfileRequest companyName(String companyName) {
        this.companyName = companyName;
        return this;
    }

    /**
     * Company Name, may be skipped
     *
     * @return companyName
     **/
    @ApiModelProperty(example = "null", value = "Company Name, may be skipped")
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public AccountProfileRequest accountTypeId(Integer accountTypeId) {
        this.accountTypeId = accountTypeId;
        return this;
    }

    /**
     * Account Type, only ID is mandatory in request
     * minimum: 1.0
     * maximum: 3.0
     *
     * @return accountTypeId
     **/
    @ApiModelProperty(example = "null", required = true, value = "Account Type, only ID is mandatory in request")
    public Integer getAccountTypeId() {
        return accountTypeId;
    }

    public void setAccountTypeId(Integer accountTypeId) {
        this.accountTypeId = accountTypeId;
    }

    public AccountProfileRequest profileDetails(AccountProfileDetailsRequest profileDetails) {
        this.profileDetails = profileDetails;
        return this;
    }

    /**
     * Profile details: Address and Contact data
     *
     * @return profileDetails
     **/
    @ApiModelProperty(example = "null", value = "Profile details: Address and Contact data")
    public AccountProfileDetailsRequest getProfileDetails() {
        return profileDetails;
    }

    public void setProfileDetails(AccountProfileDetailsRequest profileDetails) {
        this.profileDetails = profileDetails;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccountProfileRequest accountProfileRequest = (AccountProfileRequest) o;
        return Objects.equals(this.companyName, accountProfileRequest.companyName) &&
                Objects.equals(this.accountTypeId, accountProfileRequest.accountTypeId) &&
                Objects.equals(this.profileDetails, accountProfileRequest.profileDetails);
    }

    @Override
    public int hashCode() {
        return Objects.hash(companyName, accountTypeId, profileDetails);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AccountProfileRequest {\n");

        sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
        sb.append("    accountTypeId: ").append(toIndentedString(accountTypeId)).append("\n");
        sb.append("    profileDetails: ").append(toIndentedString(profileDetails)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

