/**
 * 
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.mc2.accounts.request.account_profile;

import com.clickatell.utils.StringUtils;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * CompanyContactInfoRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T14:40:21.649Z")
public class CompanyContactInfoRequest   {
  @SerializedName("cellPhone")
  private String cellPhone = "380984684022";

  @SerializedName("emailAddress")
  private String emailAddress = "company.email_" + StringUtils.generateRandomString(6) + "@fakeemail.perfectial.com";

  public CompanyContactInfoRequest cellPhone(String cellPhone) {
    this.cellPhone = cellPhone;
    return this;
  }

   /**
   * Cell phone number
   * @return cellPhone
  **/
  @ApiModelProperty(example = "null", required = true, value = "Cell phone number")
  public String getCellPhone() {
    return cellPhone;
  }

  public void setCellPhone(String cellPhone) {
    this.cellPhone = cellPhone;
  }

  public CompanyContactInfoRequest emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Email address
   * @return emailAddress
  **/
  @ApiModelProperty(example = "null", required = true, value = "Email address")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyContactInfoRequest companyContactInfoRequest = (CompanyContactInfoRequest) o;
    return Objects.equals(this.cellPhone, companyContactInfoRequest.cellPhone) &&
        Objects.equals(this.emailAddress, companyContactInfoRequest.emailAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cellPhone, emailAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyContactInfoRequest {\n");

    sb.append("    cellPhone: ").append(toIndentedString(cellPhone)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

