/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.mc2;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

public class AccountInfoResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("billingDetailsResponse")
  private BillingDetailsResponse billingDetailsResponse = null;

  public AccountInfoResponse name(String name) {
    this.name = name;
    return this;
  }

  public AccountInfoResponse(String name, String status, String id, BillingDetailsResponse billingDetailsResponse) {
    this.name = name;
    this.status = status;
    this.id = id;
    this.billingDetailsResponse = billingDetailsResponse;
  }

  public AccountInfoResponse() {
  }

  /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AccountInfoResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public AccountInfoResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AccountInfoResponse billingDetailsResponse(BillingDetailsResponse billingDetailsResponse) {
    this.billingDetailsResponse = billingDetailsResponse;
    return this;
  }

   /**
   * Get billingDetailsResponse
   * @return billingDetailsResponse
  **/
  @ApiModelProperty(example = "null", value = "")
  public BillingDetailsResponse getBillingDetailsResponse() {
    return billingDetailsResponse;
  }

  public void setBillingDetailsResponse(BillingDetailsResponse billingDetailsResponse) {
    this.billingDetailsResponse = billingDetailsResponse;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountInfoResponse accountInfoResponse = (AccountInfoResponse) o;
    return Objects.equals(this.name, accountInfoResponse.name) &&
        Objects.equals(this.status, accountInfoResponse.status) &&
        Objects.equals(this.id, accountInfoResponse.id) &&
        Objects.equals(this.billingDetailsResponse, accountInfoResponse.billingDetailsResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, id, billingDetailsResponse);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountInfoResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    billingDetailsResponse: ").append(toIndentedString(billingDetailsResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

