/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.mc2;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

public class BillingDetailsResponse {
  @SerializedName("type")
  private String type = null;

  @SerializedName("billingCurrency")
  private String billingCurrency = null;

  @SerializedName("paymentTerm")
  private String paymentTerm = null;

  @SerializedName("billingAddress")
  private String billingAddress = null;

  @SerializedName("vip")
  private Boolean vip = false;

  @SerializedName("standardDiscount")
  private Boolean standardDiscount = false;

  public BillingDetailsResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BillingDetailsResponse billingCurrency(String billingCurrency) {
    this.billingCurrency = billingCurrency;
    return this;
  }

   /**
   * Get billingCurrency
   * @return billingCurrency
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingCurrency() {
    return billingCurrency;
  }

  public void setBillingCurrency(String billingCurrency) {
    this.billingCurrency = billingCurrency;
  }

  public BillingDetailsResponse paymentTerm(String paymentTerm) {
    this.paymentTerm = paymentTerm;
    return this;
  }

   /**
   * Get paymentTerm
   * @return paymentTerm
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPaymentTerm() {
    return paymentTerm;
  }

  public void setPaymentTerm(String paymentTerm) {
    this.paymentTerm = paymentTerm;
  }

  public BillingDetailsResponse billingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBillingAddress() {
    return billingAddress;
  }

  public void setBillingAddress(String billingAddress) {
    this.billingAddress = billingAddress;
  }

  public BillingDetailsResponse vip(Boolean vip) {
    this.vip = vip;
    return this;
  }

   /**
   * Get vip
   * @return vip
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getVip() {
    return vip;
  }

  public void setVip(Boolean vip) {
    this.vip = vip;
  }

  public BillingDetailsResponse standardDiscount(Boolean standardDiscount) {
    this.standardDiscount = standardDiscount;
    return this;
  }

   /**
   * Get standardDiscount
   * @return standardDiscount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getStandardDiscount() {
    return standardDiscount;
  }

  public void setStandardDiscount(Boolean standardDiscount) {
    this.standardDiscount = standardDiscount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingDetailsResponse billingDetailsResponse = (BillingDetailsResponse) o;
    return Objects.equals(this.type, billingDetailsResponse.type) &&
        Objects.equals(this.billingCurrency, billingDetailsResponse.billingCurrency) &&
        Objects.equals(this.paymentTerm, billingDetailsResponse.paymentTerm) &&
        Objects.equals(this.billingAddress, billingDetailsResponse.billingAddress) &&
        Objects.equals(this.vip, billingDetailsResponse.vip) &&
        Objects.equals(this.standardDiscount, billingDetailsResponse.standardDiscount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, billingCurrency, paymentTerm, billingAddress, vip, standardDiscount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingDetailsResponse {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    billingCurrency: ").append(toIndentedString(billingCurrency)).append("\n");
    sb.append("    paymentTerm: ").append(toIndentedString(paymentTerm)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    vip: ").append(toIndentedString(vip)).append("\n");
    sb.append("    standardDiscount: ").append(toIndentedString(standardDiscount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

