/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.integration;

import com.clickatell.models.user_profiles.UserProfile;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * IntegrationResponse
 */
public class IntegrationUserLoginMC2Response {
  @SerializedName("responseJson")
  private UserProfile responseJson = null;

  @SerializedName("statusCode")
  private Integer statusCode = null;

  public IntegrationUserLoginMC2Response responseJson(UserProfile responseJson) {
    this.responseJson = responseJson;
    return this;
  }

   /**
   * Get responseJson
   * @return responseJson
  **/
  @ApiModelProperty(example = "null", value = "")
  public UserProfile getResponseJson() {
    return responseJson;
  }

  public void setResponseJson(UserProfile responseJson) {
    this.responseJson = responseJson;
  }

  public IntegrationUserLoginMC2Response statusCode(Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegrationUserLoginMC2Response integrationResponse = (IntegrationUserLoginMC2Response) o;
    return Objects.equals(this.responseJson, integrationResponse.responseJson) &&
        Objects.equals(this.statusCode, integrationResponse.statusCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseJson, statusCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegrationResponse {\n");
    
    sb.append("    responseJson: ").append(toIndentedString(responseJson)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

