/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.integration;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ListIntegrationResponseV6
 */
public class ListIntegrationResponseV6   {
  @SerializedName("integrations")
  private List<IntegrationResponseV6> integrations = new ArrayList<IntegrationResponseV6>();

  public ListIntegrationResponseV6 integrations(List<IntegrationResponseV6> integrations) {
    this.integrations = integrations;
    return this;
  }

  public ListIntegrationResponseV6 addIntegrationsItem(IntegrationResponseV6 integrationsItem) {
    this.integrations.add(integrationsItem);
    return this;
  }

   /**
   * Get integrations
   * @return integrations
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<IntegrationResponseV6> getIntegrations() {
    return integrations;
  }

  public void setIntegrations(List<IntegrationResponseV6> integrations) {
    this.integrations = integrations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListIntegrationResponseV6 listIntegrationResponseV6 = (ListIntegrationResponseV6) o;
    return Objects.equals(this.integrations, listIntegrationResponseV6.integrations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(integrations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListIntegrationResponseV6 {\n");
    
    sb.append("    integrations: ").append(toIndentedString(integrations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

