/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.cards;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

public class TouchCardResponseV3 {
  @SerializedName("cardName")
  private String cardName = null;

  @SerializedName("platforms")
  private List<PlatformDtoV3> platforms = new ArrayList<PlatformDtoV3>();

  public TouchCardResponseV3 cardName(String cardName) {
    this.cardName = cardName;
    return this;
  }

  public TouchCardResponseV3() {
  }

  public TouchCardResponseV3(String cardName, List<PlatformDtoV3> platforms) {
    this.cardName = cardName;
    this.platforms = platforms;
  }

  /**
   * Get cardName
   * @return cardName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCardName() {
    return cardName;
  }

  public void setCardName(String cardName) {
    this.cardName = cardName;
  }

  public TouchCardResponseV3 platforms(List<PlatformDtoV3> platforms) {
    this.platforms = platforms;
    return this;
  }

  public TouchCardResponseV3 addPlatformsItem(PlatformDtoV3 platformsItem) {
    this.platforms.add(platformsItem);
    return this;
  }

   /**
   * Get platforms
   * @return platforms
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PlatformDtoV3> getPlatforms() {
    return platforms;
  }

  public void setPlatforms(List<PlatformDtoV3> platforms) {
    this.platforms = platforms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TouchCardResponseV3 touchCardResponseV3 = (TouchCardResponseV3) o;
    return Objects.equals(this.cardName, touchCardResponseV3.cardName) &&
        Objects.equals(this.platforms, touchCardResponseV3.platforms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardName, platforms);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TouchCardResponseV3 {\n");
    
    sb.append("    cardName: ").append(toIndentedString(cardName)).append("\n");
    sb.append("    platforms: ").append(toIndentedString(platforms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

