/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.appconfig;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

public class XmppConfigResponseV5 {
  @SerializedName("domain")
  private String domain = null;

  @SerializedName("socketConnectorPort")
  private Integer socketConnectorPort = null;

  @SerializedName("hostname")
  private String hostname = null;

  @SerializedName("boshConnectorPort")
  private Integer boshConnectorPort = null;

  public XmppConfigResponseV5 domain(String domain) {
    this.domain = domain;
    return this;
  }

   /**
   * Get domain
   * @return domain
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDomain() {
    return domain;
  }

  public void setDomain(String domain) {
    this.domain = domain;
  }

  public XmppConfigResponseV5 socketConnectorPort(Integer socketConnectorPort) {
    this.socketConnectorPort = socketConnectorPort;
    return this;
  }

   /**
   * Get socketConnectorPort
   * @return socketConnectorPort
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSocketConnectorPort() {
    return socketConnectorPort;
  }

  public void setSocketConnectorPort(Integer socketConnectorPort) {
    this.socketConnectorPort = socketConnectorPort;
  }

  public XmppConfigResponseV5 hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public XmppConfigResponseV5 boshConnectorPort(Integer boshConnectorPort) {
    this.boshConnectorPort = boshConnectorPort;
    return this;
  }

   /**
   * Get boshConnectorPort
   * @return boshConnectorPort
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getBoshConnectorPort() {
    return boshConnectorPort;
  }

  public void setBoshConnectorPort(Integer boshConnectorPort) {
    this.boshConnectorPort = boshConnectorPort;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XmppConfigResponseV5 xmppConfigResponseV5 = (XmppConfigResponseV5) o;
    return Objects.equals(this.domain, xmppConfigResponseV5.domain) &&
        Objects.equals(this.socketConnectorPort, xmppConfigResponseV5.socketConnectorPort) &&
        Objects.equals(this.hostname, xmppConfigResponseV5.hostname) &&
        Objects.equals(this.boshConnectorPort, xmppConfigResponseV5.boshConnectorPort);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domain, socketConnectorPort, hostname, boshConnectorPort);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XmppConfigResponseV5 {\n");
    
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    socketConnectorPort: ").append(toIndentedString(socketConnectorPort)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    boshConnectorPort: ").append(toIndentedString(boshConnectorPort)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

