/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, VersionFlow 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.user_profile;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * ListUserProfilesResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-06T15:43:34.475Z")
public class ListUserProfilesResponse {
  @SerializedName("userProfiles")
  private List<UserProfileResponse> userProfiles = new ArrayList<UserProfileResponse>();

  public ListUserProfilesResponse userProfiles(List<UserProfileResponse> userProfiles) {
    this.userProfiles = userProfiles;
    return this;
  }

  public ListUserProfilesResponse addUserProfilesItem(UserProfileResponse userProfilesItem) {
    this.userProfiles.add(userProfilesItem);
    return this;
  }

   /**
   * Get userProfiles
   * @return userProfiles
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<UserProfileResponse> getUserProfiles() {
    return userProfiles;
  }

  public void setUserProfiles(List<UserProfileResponse> userProfiles) {
    this.userProfiles = userProfiles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListUserProfilesResponse listUserProfilesResponse = (ListUserProfilesResponse) o;
    return Objects.equals(this.userProfiles, listUserProfilesResponse.userProfiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userProfiles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListUserProfilesResponse {\n");
    
    sb.append("    userProfiles: ").append(toIndentedString(userProfiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

