/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, VersionFlow 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * AddressResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-06T15:43:34.475Z")
public class AddressResponse {
  @SerializedName("firstAddressLine")
  private String firstAddressLine = null;

  @SerializedName("secondAddressLine")
  private String secondAddressLine = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("stateOrProvince")
  private String stateOrProvince = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("lat")
  private Float lat = null;

  @SerializedName("lng")
  private Float lng = null;

  @SerializedName("businessHours")
  private List<AddressBusinessHourDto> businessHours = new ArrayList<AddressBusinessHourDto>();

  @SerializedName("phones")
  private List<Phone> phones = new ArrayList<Phone>();

  @SerializedName("id")
  private String id = null;

  public AddressResponse firstAddressLine(String firstAddressLine) {
    this.firstAddressLine = firstAddressLine;
    return this;
  }

   /**
   * Get firstAddressLine
   * @return firstAddressLine
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getFirstAddressLine() {
    return firstAddressLine;
  }

  public void setFirstAddressLine(String firstAddressLine) {
    this.firstAddressLine = firstAddressLine;
  }

  public AddressResponse secondAddressLine(String secondAddressLine) {
    this.secondAddressLine = secondAddressLine;
    return this;
  }

   /**
   * Get secondAddressLine
   * @return secondAddressLine
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSecondAddressLine() {
    return secondAddressLine;
  }

  public void setSecondAddressLine(String secondAddressLine) {
    this.secondAddressLine = secondAddressLine;
  }

  public AddressResponse city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AddressResponse stateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
    return this;
  }

   /**
   * Get stateOrProvince
   * @return stateOrProvince
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStateOrProvince() {
    return stateOrProvince;
  }

  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public AddressResponse postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public AddressResponse lat(Float lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getLat() {
    return lat;
  }

  public void setLat(Float lat) {
    this.lat = lat;
  }

  public AddressResponse lng(Float lng) {
    this.lng = lng;
    return this;
  }

   /**
   * Get lng
   * @return lng
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getLng() {
    return lng;
  }

  public void setLng(Float lng) {
    this.lng = lng;
  }

  public AddressResponse businessHours(List<AddressBusinessHourDto> businessHours) {
    this.businessHours = businessHours;
    return this;
  }

  public AddressResponse addBusinessHoursItem(AddressBusinessHourDto businessHoursItem) {
    this.businessHours.add(businessHoursItem);
    return this;
  }

   /**
   * Get businessHours
   * @return businessHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressBusinessHourDto> getBusinessHours() {
    return businessHours;
  }

  public void setBusinessHours(List<AddressBusinessHourDto> businessHours) {
    this.businessHours = businessHours;
  }

  public AddressResponse phones(List<Phone> phones) {
    this.phones = phones;
    return this;
  }

  public AddressResponse addPhonesItem(Phone phonesItem) {
    this.phones.add(phonesItem);
    return this;
  }

   /**
   * Get phones
   * @return phones
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Phone> getPhones() {
    return phones;
  }

  public void setPhones(List<Phone> phones) {
    this.phones = phones;
  }

  public AddressResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressResponse addressResponse = (AddressResponse) o;
    return Objects.equals(this.firstAddressLine, addressResponse.firstAddressLine) &&
        Objects.equals(this.secondAddressLine, addressResponse.secondAddressLine) &&
        Objects.equals(this.city, addressResponse.city) &&
        Objects.equals(this.stateOrProvince, addressResponse.stateOrProvince) &&
        Objects.equals(this.postalCode, addressResponse.postalCode) &&
        Objects.equals(this.lat, addressResponse.lat) &&
        Objects.equals(this.lng, addressResponse.lng) &&
        Objects.equals(this.businessHours, addressResponse.businessHours) &&
        Objects.equals(this.phones, addressResponse.phones) &&
        Objects.equals(this.id, addressResponse.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstAddressLine, secondAddressLine, city, stateOrProvince, postalCode, lat, lng, businessHours, phones, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressResponse {\n");
    
    sb.append("    firstAddressLine: ").append(toIndentedString(firstAddressLine)).append("\n");
    sb.append("    secondAddressLine: ").append(toIndentedString(secondAddressLine)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    businessHours: ").append(toIndentedString(businessHours)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

