/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * AddressDtoV3
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-06T14:49:12.583Z")
public class AddressDtoV3 {
  @SerializedName("firstAddressLine")
  private String firstAddressLine = null;

  @SerializedName("secondAddressLine")
  private String secondAddressLine = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("stateOrProvince")
  private String stateOrProvince = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("lat")
  private Float lat = null;

  @SerializedName("lng")
  private Float lng = null;

  @SerializedName("businessHours")
  private List<AddressBusinessHourDtoV2> businessHours = new ArrayList<AddressBusinessHourDtoV2>();

  @SerializedName("phones")
  private List<AddressPhoneDtoV2> phones = new ArrayList<AddressPhoneDtoV2>();

  public AddressDtoV3 firstAddressLine(String firstAddressLine) {
    this.firstAddressLine = firstAddressLine;
    return this;
  }

   /**
   * Get firstAddressLine
   * @return firstAddressLine
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getFirstAddressLine() {
    return firstAddressLine;
  }

  public void setFirstAddressLine(String firstAddressLine) {
    this.firstAddressLine = firstAddressLine;
  }

  public AddressDtoV3 secondAddressLine(String secondAddressLine) {
    this.secondAddressLine = secondAddressLine;
    return this;
  }

   /**
   * Get secondAddressLine
   * @return secondAddressLine
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getSecondAddressLine() {
    return secondAddressLine;
  }

  public void setSecondAddressLine(String secondAddressLine) {
    this.secondAddressLine = secondAddressLine;
  }

  public AddressDtoV3 city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AddressDtoV3 stateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
    return this;
  }

   /**
   * Get stateOrProvince
   * @return stateOrProvince
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStateOrProvince() {
    return stateOrProvince;
  }

  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public AddressDtoV3 postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public AddressDtoV3 lat(Float lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getLat() {
    return lat;
  }

  public void setLat(Float lat) {
    this.lat = lat;
  }

  public AddressDtoV3 lng(Float lng) {
    this.lng = lng;
    return this;
  }

   /**
   * Get lng
   * @return lng
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getLng() {
    return lng;
  }

  public void setLng(Float lng) {
    this.lng = lng;
  }

  public AddressDtoV3 businessHours(List<AddressBusinessHourDtoV2> businessHours) {
    this.businessHours = businessHours;
    return this;
  }

  public AddressDtoV3 addBusinessHoursItem(AddressBusinessHourDtoV2 businessHoursItem) {
    this.businessHours.add(businessHoursItem);
    return this;
  }

   /**
   * Get businessHours
   * @return businessHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressBusinessHourDtoV2> getBusinessHours() {
    return businessHours;
  }

  public void setBusinessHours(List<AddressBusinessHourDtoV2> businessHours) {
    this.businessHours = businessHours;
  }

  public AddressDtoV3 phones(List<AddressPhoneDtoV2> phones) {
    this.phones = phones;
    return this;
  }

  public AddressDtoV3 addPhonesItem(AddressPhoneDtoV2 phonesItem) {
    this.phones.add(phonesItem);
    return this;
  }

   /**
   * Get phones
   * @return phones
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressPhoneDtoV2> getPhones() {
    return phones;
  }

  public void setPhones(List<AddressPhoneDtoV2> phones) {
    this.phones = phones;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressDtoV3 addressDtoV3 = (AddressDtoV3) o;
    return Objects.equals(this.firstAddressLine, addressDtoV3.firstAddressLine) &&
        Objects.equals(this.secondAddressLine, addressDtoV3.secondAddressLine) &&
        Objects.equals(this.city, addressDtoV3.city) &&
        Objects.equals(this.stateOrProvince, addressDtoV3.stateOrProvince) &&
        Objects.equals(this.postalCode, addressDtoV3.postalCode) &&
        Objects.equals(this.lat, addressDtoV3.lat) &&
        Objects.equals(this.lng, addressDtoV3.lng) &&
        Objects.equals(this.businessHours, addressDtoV3.businessHours) &&
        Objects.equals(this.phones, addressDtoV3.phones);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstAddressLine, secondAddressLine, city, stateOrProvince, postalCode, lat, lng, businessHours, phones);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressDtoV3 {\n");
    
    sb.append("    firstAddressLine: ").append(toIndentedString(firstAddressLine)).append("\n");
    sb.append("    secondAddressLine: ").append(toIndentedString(secondAddressLine)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lng: ").append(toIndentedString(lng)).append("\n");
    sb.append("    businessHours: ").append(toIndentedString(businessHours)).append("\n");
    sb.append("    phones: ").append(toIndentedString(phones)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

