/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, VersionFlow 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


/**
 * DepartmentResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-06T15:43:34.475Z")
public class DepartmentResponse {
  public DepartmentResponse() {
    this.tenantId = tenantId;
    this.name = name;
    this.description = description;
    this.sessionsCapacity = sessionsCapacity;
    this.id = id;
    this.createdDate = createdDate;
    this.modifiedDate = modifiedDate;
    this.agents = new ArrayList<AgentNoDepartmentsResponse>();
  }

  public DepartmentResponse(String tenantId, String name, String description, Integer sessionsCapacity, String id, Long createdDate, Long modifiedDate, List<AgentNoDepartmentsResponse> agents) {
    this.tenantId = tenantId;
    this.name = name;
    this.description = description;
    this.sessionsCapacity = sessionsCapacity;
    this.id = id;
    this.createdDate = createdDate;
    this.modifiedDate = modifiedDate;
    this.agents = agents;
  }

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sessionsCapacity")
  private Integer sessionsCapacity = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("createdDate")
  private Long createdDate = null;

  @SerializedName("modifiedDate")
  private Long modifiedDate = null;

  @SerializedName("agents")
  private List<AgentNoDepartmentsResponse> agents = new ArrayList<AgentNoDepartmentsResponse>();

  public DepartmentResponse tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Get tenantId
   * @return tenantId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public DepartmentResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DepartmentResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DepartmentResponse sessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
    return this;
  }

   /**
   * Get sessionsCapacity
   * @return sessionsCapacity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSessionsCapacity() {
    return sessionsCapacity;
  }

  public void setSessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
  }

  public DepartmentResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DepartmentResponse createdDate(Long createdDate) {
    this.createdDate = createdDate;
    return this;
  }

   /**
   * Get createdDate
   * @return createdDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedDate() {
    return createdDate;
  }

  public void setCreatedDate(Long createdDate) {
    this.createdDate = createdDate;
  }

  public DepartmentResponse modifiedDate(Long modifiedDate) {
    this.modifiedDate = modifiedDate;
    return this;
  }

   /**
   * Get modifiedDate
   * @return modifiedDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getModifiedDate() {
    return modifiedDate;
  }

  public void setModifiedDate(Long modifiedDate) {
    this.modifiedDate = modifiedDate;
  }

  public DepartmentResponse agents(List<AgentNoDepartmentsResponse> agents) {
    this.agents = agents;
    return this;
  }

  public DepartmentResponse addAgentsItem(AgentNoDepartmentsResponse agentsItem) {
    this.agents.add(agentsItem);
    return this;
  }

   /**
   * Get agents
   * @return agents
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AgentNoDepartmentsResponse> getAgents() {
    return agents;
  }

  public void setAgents(List<AgentNoDepartmentsResponse> agents) {
    this.agents = agents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepartmentResponse departmentResponse = (DepartmentResponse) o;
    return Objects.equals(this.tenantId, departmentResponse.tenantId) &&
        Objects.equals(this.name, departmentResponse.name) &&
        Objects.equals(this.description, departmentResponse.description) &&
        Objects.equals(this.sessionsCapacity, departmentResponse.sessionsCapacity) &&
        Objects.equals(this.id, departmentResponse.id) &&
        Objects.equals(this.createdDate, departmentResponse.createdDate) &&
        Objects.equals(this.modifiedDate, departmentResponse.modifiedDate) &&
        Objects.equals(this.agents, departmentResponse.agents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantId, name, description, sessionsCapacity, id, createdDate, modifiedDate, agents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepartmentResponse {\n");
    
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
    sb.append("    modifiedDate: ").append(toIndentedString(modifiedDate)).append("\n");
    sb.append("    agents: ").append(toIndentedString(agents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

