/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ListAddressBusinessHoursResponse
 */
public class ListAddressBusinessHoursResponse {
  @SerializedName("addressBusinessHours")
  private List<AddressBusinessHourResponse> addressBusinessHours = new ArrayList<AddressBusinessHourResponse>();

  public ListAddressBusinessHoursResponse addressBusinessHours(List<AddressBusinessHourResponse> addressBusinessHours) {
    this.addressBusinessHours = addressBusinessHours;
    return this;
  }

  public ListAddressBusinessHoursResponse addAddressBusinessHoursItem(AddressBusinessHourResponse addressBusinessHoursItem) {
    this.addressBusinessHours.add(addressBusinessHoursItem);
    return this;
  }

   /**
   * Get addressBusinessHours
   * @return addressBusinessHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressBusinessHourResponse> getAddressBusinessHours() {
    return addressBusinessHours;
  }

  public void setAddressBusinessHours(List<AddressBusinessHourResponse> addressBusinessHours) {
    this.addressBusinessHours = addressBusinessHours;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListAddressBusinessHoursResponse listAddressBusinessHoursResponse = (ListAddressBusinessHoursResponse) o;
    return Objects.equals(this.addressBusinessHours, listAddressBusinessHoursResponse.addressBusinessHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressBusinessHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListAddressBusinessHoursResponse {\n");
    
    sb.append("    addressBusinessHours: ").append(toIndentedString(addressBusinessHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

