/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, VersionFlow 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;

import com.touch.utils.StringUtils;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;



@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-02T11:18:28.144Z")
public class TenantRequest extends Tenant{

  public TenantRequest() {
    this.accountId = "2c9f830756e0e99f0156e13ed4ed003d";
    this.tenantOrgName = StringUtils.generateRandomString(10) + "Test1";
    this.contactEmail = StringUtils.generateRandomString(10) + "@fake.perfectial.com";
    this.state = StateEnum.ACTIVE;
    this.description = StringUtils.generateRandomString(10);
    this.shortDescription = StringUtils.generateRandomString(10);
    this.tenantJid = StringUtils.generateRandomString(7) + "11@fake.perfectial.com";
    this.tenantBotJid = StringUtils.generateRandomString(7) + "11@fake.perfectial.com";
    this.category = "Banking";
    this.tenantTags = new ArrayList<String>();
    this.sessionsCapacity = 5;
    this.tenantAddresses = new ArrayList<AddressDto>();
    tenantAddresses.add(new AddressDto());
    this.tenantFaqs = new ArrayList<TenantFaqDto>();
    this.tenantColours = new ArrayList<TenantColourDto>();
    tenantColours.add(new TenantColourDto());
  }

  public TenantRequest(String accountId, String tenantOrgName, String contactEmail, StateEnum state,
                       String description, String shortDescription, String tenantJid, String tenantBotJid, String category, List<String> tenantTags,
                       Integer sessionsCapacity, List<AddressDto> tenantAddresses, List<TenantFaqDto> tenantFaqs) {
    this.accountId = accountId;
    this.tenantOrgName = tenantOrgName;
    this.contactEmail = contactEmail;
    this.state = state;
    this.description = description;
    this.shortDescription = shortDescription;
    this.tenantJid = tenantJid;
    this.tenantBotJid = tenantBotJid;
    this.category = category;
    this.tenantTags = tenantTags;
    this.sessionsCapacity = sessionsCapacity;
    this.tenantAddresses = tenantAddresses;
    this.tenantFaqs = tenantFaqs;
  }


  @SerializedName("accountId")
  private String accountId = null;
  @SerializedName("tenantAddresses")
  protected List<AddressDto> tenantAddresses = new ArrayList<AddressDto>();



  @SerializedName("tenantFaqs")
  private List<TenantFaqDto> tenantFaqs = new ArrayList<TenantFaqDto>();
  @SerializedName("tenantFaqs")
  private List<TenantColourDto> tenantColours = new ArrayList<TenantColourDto>();

  public List<TenantColourDto> getTenantColours() {
    return tenantColours;
  }

  public void setTenantColours(TenantColourDto tenantColour) {
    this.tenantColours.add(tenantColour);
  }

  public TenantRequest accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public TenantRequest tenantOrgName(String tenantOrgName) {
    this.tenantOrgName = tenantOrgName;
    return this;
  }

   /**
   * Get tenantOrgName
   * @return tenantOrgName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantOrgName() {
    return tenantOrgName;
  }

  public void setTenantOrgName(String tenantOrgName) {
    this.tenantOrgName = tenantOrgName;
  }

  public TenantRequest contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * Get contactEmail
   * @return contactEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public TenantRequest state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public TenantRequest description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TenantRequest shortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * Get shortDescription
   * @return shortDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public TenantRequest tenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
    return this;
  }

   /**
   * Get tenantJid
   * @return tenantJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantJid() {
    return tenantJid;
  }

  public void setTenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
  }

  public TenantRequest tenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
    return this;
  }

   /**
   * Get tenantBotJid
   * @return tenantBotJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantBotJid() {
    return tenantBotJid;
  }

  public void setTenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
  }


  public TenantRequest category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public TenantRequest tenantTags(List<String> tenantTags) {
    this.tenantTags = tenantTags;
    return this;
  }

  public TenantRequest addTenantTagsItem(String tenantTagsItem) {
    this.tenantTags.add(tenantTagsItem);
    return this;
  }

   /**
   * Get tenantTags
   * @return tenantTags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTenantTags() {
    return tenantTags;
  }

  public void setTenantTags(List<String> tenantTags) {
    this.tenantTags = tenantTags;
  }

  public TenantRequest sessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
    return this;
  }

   /**
   * Get sessionsCapacity
   * @return sessionsCapacity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSessionsCapacity() {
    return sessionsCapacity;
  }

  public void setSessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
  }

  public TenantRequest tenantAddresses(List<AddressDto> tenantAddresses) {
    this.tenantAddresses = tenantAddresses;
    return this;
  }

  public TenantRequest addTenantAddressesItem(AddressDto tenantAddressesItem) {
    this.tenantAddresses.add(tenantAddressesItem);
    return this;
  }

   /**
   * Get tenantAddresses
   * @return tenantAddresses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressDto> getTenantAddresses() {
    return tenantAddresses;
  }

  public void setTenantAddresses(List<AddressDto> tenantAddresses) {
    this.tenantAddresses = tenantAddresses;
  }


  public TenantRequest tenantFaqs(List<TenantFaqDto> tenantFaqs) {
    this.tenantFaqs = tenantFaqs;
    return this;
  }

  public TenantRequest addTenantFaqsItem(TenantFaqDto tenantFaqsItem) {
    this.tenantFaqs.add(tenantFaqsItem);
    return this;
  }

   /**
   * Get tenantFaqs
   * @return tenantFaqs
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<TenantFaqDto> getTenantFaqs() {
    return tenantFaqs;
  }

  public void setTenantFaqs(List<TenantFaqDto> tenantFaqs) {
    this.tenantFaqs = tenantFaqs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || (getClass() != o.getClass() && TenantResponse.class != o.getClass() && TenantUpdateDto.class != o.getClass())) {
      return false;
    }
    Tenant tenantRequest = (Tenant) o;
    return Objects.equals(this.tenantOrgName, tenantRequest.tenantOrgName) &&
            Objects.equals(this.contactEmail, tenantRequest.contactEmail) &&
            Objects.equals(this.state, tenantRequest.state) &&
            Objects.equals(this.description, tenantRequest.description) &&
            Objects.equals(this.shortDescription, tenantRequest.shortDescription) &&
            Objects.equals(this.tenantJid, tenantRequest.tenantJid) &&
            Objects.equals(this.tenantBotJid, tenantRequest.tenantBotJid) &&
            Objects.equals(this.category, tenantRequest.category) &&
            Objects.equals(this.tenantTags, tenantRequest.tenantTags) &&
            Objects.equals(this.sessionsCapacity, tenantRequest.sessionsCapacity);

  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, tenantOrgName, contactEmail, state, description, shortDescription, tenantJid, tenantBotJid, category, tenantTags, sessionsCapacity, tenantAddresses, tenantFaqs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantRequestV1 {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    tenantOrgName: ").append(toIndentedString(tenantOrgName)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    tenantJid: ").append(toIndentedString(tenantJid)).append("\n");
    sb.append("    tenantBotJid: ").append(toIndentedString(tenantBotJid)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    tenantTags: ").append(toIndentedString(tenantTags)).append("\n");
    sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
    sb.append("    tenantAddresses: ").append(toIndentedString(tenantAddresses)).append("\n");
    sb.append("    tenantFaqs: ").append(toIndentedString(tenantFaqs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

