/**
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import com.touch.models.touch.department.DepartmentResponse;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;


/**
 * TenantResponseV4
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-11-15T09:51:42.574Z")
public class TenantResponseV4 {
    @SerializedName("accountId")
    private String accountId = null;

    @SerializedName("tenantOrgName")
    private String tenantOrgName = null;

    @SerializedName("contactEmail")
    private String contactEmail = null;

    /**
     * Gets or Sets state
     */
    public enum StateEnum {
        @SerializedName("ACTIVE")
        ACTIVE("ACTIVE"),

        @SerializedName("INACTIVE")
        INACTIVE("INACTIVE");

        private String value;

        StateEnum(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

    @SerializedName("state")
    private StateEnum state = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("shortDescription")
    private String shortDescription = null;

    @SerializedName("tenantJid")
    private String tenantJid = null;

    @SerializedName("tenantBotJid")
    private String tenantBotJid = null;

    @SerializedName("category")
    private String category = null;

    @SerializedName("tenantTags")
    private List<String> tenantTags = new ArrayList<String>();

    @SerializedName("sessionsCapacity")
    private Integer sessionsCapacity = null;

    @SerializedName("tenantFaqs")
    private List<TenantFaq> tenantFaqs = new ArrayList<TenantFaq>();

    @SerializedName("tenantColours")
    private List<TenantColour> tenantColours = new ArrayList<TenantColour>();

    @SerializedName("tenantAddresses")
    private List<AddressResponse> tenantAddresses = new ArrayList<AddressResponse>();

    @SerializedName("id")
    private String id = null;

    @SerializedName("tenantResources")
    private List<String> tenantResources = new ArrayList<String>();

    @SerializedName("departments")
    private List<DepartmentResponse> departments = new ArrayList<DepartmentResponse>();

    public TenantResponseV4 accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Get accountId
     * @return accountId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public TenantResponseV4 tenantOrgName(String tenantOrgName) {
        this.tenantOrgName = tenantOrgName;
        return this;
    }

    /**
     * Get tenantOrgName
     * @return tenantOrgName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTenantOrgName() {
        return tenantOrgName;
    }

    public void setTenantOrgName(String tenantOrgName) {
        this.tenantOrgName = tenantOrgName;
    }

    public TenantResponseV4 contactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
        return this;
    }

    /**
     * Get contactEmail
     * @return contactEmail
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public TenantResponseV4 state(StateEnum state) {
        this.state = state;
        return this;
    }

    /**
     * Get state
     * @return state
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public StateEnum getState() {
        return state;
    }

    public void setState(StateEnum state) {
        this.state = state;
    }

    public TenantResponseV4 description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TenantResponseV4 shortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
        return this;
    }

    /**
     * Get shortDescription
     * @return shortDescription
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public TenantResponseV4 tenantJid(String tenantJid) {
        this.tenantJid = tenantJid;
        return this;
    }

    /**
     * Get tenantJid
     * @return tenantJid
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTenantJid() {
        return tenantJid;
    }

    public void setTenantJid(String tenantJid) {
        this.tenantJid = tenantJid;
    }

    public TenantResponseV4 tenantBotJid(String tenantBotJid) {
        this.tenantBotJid = tenantBotJid;
        return this;
    }

    /**
     * Get tenantBotJid
     * @return tenantBotJid
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTenantBotJid() {
        return tenantBotJid;
    }

    public void setTenantBotJid(String tenantBotJid) {
        this.tenantBotJid = tenantBotJid;
    }

    public TenantResponseV4 category(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get category
     * @return category
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public TenantResponseV4 tenantTags(List<String> tenantTags) {
        this.tenantTags = tenantTags;
        return this;
    }

    public TenantResponseV4 addTenantTagsItem(String tenantTagsItem) {
        this.tenantTags.add(tenantTagsItem);
        return this;
    }

    /**
     * Get tenantTags
     * @return tenantTags
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<String> getTenantTags() {
        return tenantTags;
    }

    public void setTenantTags(List<String> tenantTags) {
        this.tenantTags = tenantTags;
    }

    public TenantResponseV4 sessionsCapacity(Integer sessionsCapacity) {
        this.sessionsCapacity = sessionsCapacity;
        return this;
    }

    /**
     * Get sessionsCapacity
     * @return sessionsCapacity
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getSessionsCapacity() {
        return sessionsCapacity;
    }

    public void setSessionsCapacity(Integer sessionsCapacity) {
        this.sessionsCapacity = sessionsCapacity;
    }

    public TenantResponseV4 tenantFaqs(List<TenantFaq> tenantFaqs) {
        this.tenantFaqs = tenantFaqs;
        return this;
    }

    public TenantResponseV4 addTenantFaqsItem(TenantFaq tenantFaqsItem) {
        this.tenantFaqs.add(tenantFaqsItem);
        return this;
    }

    /**
     * Get tenantFaqs
     * @return tenantFaqs
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<TenantFaq> getTenantFaqs() {
        return tenantFaqs;
    }

    public void setTenantFaqs(List<TenantFaq> tenantFaqs) {
        this.tenantFaqs = tenantFaqs;
    }

    public TenantResponseV4 tenantColours(List<TenantColour> tenantColours) {
        this.tenantColours = tenantColours;
        return this;
    }

    public TenantResponseV4 addTenantColoursItem(TenantColour tenantColoursItem) {
        this.tenantColours.add(tenantColoursItem);
        return this;
    }

    /**
     * Get tenantColours
     * @return tenantColours
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<TenantColour> getTenantColours() {
        return tenantColours;
    }

    public void setTenantColours(List<TenantColour> tenantColours) {
        this.tenantColours = tenantColours;
    }

    public TenantResponseV4 tenantAddresses(List<AddressResponse> tenantAddresses) {
        this.tenantAddresses = tenantAddresses;
        return this;
    }

    public TenantResponseV4 addTenantAddressesItem(AddressResponse tenantAddressesItem) {
        this.tenantAddresses.add(tenantAddressesItem);
        return this;
    }

    /**
     * Get tenantAddresses
     * @return tenantAddresses
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<AddressResponse> getTenantAddresses() {
        return tenantAddresses;
    }

    public void setTenantAddresses(List<AddressResponse> tenantAddresses) {
        this.tenantAddresses = tenantAddresses;
    }

    public TenantResponseV4 id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public TenantResponseV4 tenantResources(List<String> tenantResources) {
        this.tenantResources = tenantResources;
        return this;
    }

    public TenantResponseV4 addTenantResourcesItem(String tenantResourcesItem) {
        this.tenantResources.add(tenantResourcesItem);
        return this;
    }

    /**
     * Get tenantResources
     * @return tenantResources
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<String> getTenantResources() {
        return tenantResources;
    }

    public void setTenantResources(List<String> tenantResources) {
        this.tenantResources = tenantResources;
    }

    public TenantResponseV4 departments(List<DepartmentResponse> departments) {
        this.departments = departments;
        return this;
    }

    public TenantResponseV4 addDepartmentsItem(DepartmentResponse departmentsItem) {
        this.departments.add(departmentsItem);
        return this;
    }

    /**
     * Get departments
     * @return departments
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<DepartmentResponse> getDepartments() {
        return departments;
    }

    public void setDepartments(List<DepartmentResponse> departments) {
        this.departments = departments;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TenantResponseV4 tenantResponseV4 = (TenantResponseV4) o;
        return Objects.equals(this.accountId, tenantResponseV4.accountId) &&
                Objects.equals(this.tenantOrgName, tenantResponseV4.tenantOrgName) &&
                Objects.equals(this.contactEmail, tenantResponseV4.contactEmail) &&
                Objects.equals(this.state, tenantResponseV4.state) &&
                Objects.equals(this.description, tenantResponseV4.description) &&
                Objects.equals(this.shortDescription, tenantResponseV4.shortDescription) &&
                Objects.equals(this.tenantJid, tenantResponseV4.tenantJid) &&
                Objects.equals(this.tenantBotJid, tenantResponseV4.tenantBotJid) &&
                Objects.equals(this.category, tenantResponseV4.category) &&
                Objects.equals(this.tenantTags, tenantResponseV4.tenantTags) &&
                Objects.equals(this.sessionsCapacity, tenantResponseV4.sessionsCapacity) &&
                Objects.equals(this.tenantFaqs, tenantResponseV4.tenantFaqs) &&
                Objects.equals(this.tenantColours, tenantResponseV4.tenantColours) &&
                Objects.equals(this.tenantAddresses, tenantResponseV4.tenantAddresses) &&
                Objects.equals(this.id, tenantResponseV4.id) &&
                Objects.equals(this.tenantResources, tenantResponseV4.tenantResources) &&
                Objects.equals(this.departments, tenantResponseV4.departments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accountId, tenantOrgName, contactEmail, state, description, shortDescription, tenantJid, tenantBotJid, category, tenantTags, sessionsCapacity, tenantFaqs, tenantColours, tenantAddresses, id, tenantResources, departments);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TenantResponseV4 {\n");

        sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
        sb.append("    tenantOrgName: ").append(toIndentedString(tenantOrgName)).append("\n");
        sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
        sb.append("    tenantJid: ").append(toIndentedString(tenantJid)).append("\n");
        sb.append("    tenantBotJid: ").append(toIndentedString(tenantBotJid)).append("\n");
        sb.append("    category: ").append(toIndentedString(category)).append("\n");
        sb.append("    tenantTags: ").append(toIndentedString(tenantTags)).append("\n");
        sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
        sb.append("    tenantFaqs: ").append(toIndentedString(tenantFaqs)).append("\n");
        sb.append("    tenantColours: ").append(toIndentedString(tenantColours)).append("\n");
        sb.append("    tenantAddresses: ").append(toIndentedString(tenantAddresses)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    tenantResources: ").append(toIndentedString(tenantResources)).append("\n");
        sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

