/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TenantTbotResponseV5
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-13T08:15:05.879Z")
public class TenantTbotResponseV5 {
  @SerializedName("tenantBotJid")
  private String tenantBotJid = null;

  @SerializedName("botPassword")
  private String botPassword = null;

  @SerializedName("csBotName")
  private String csBotName = null;

  public TenantTbotResponseV5 tenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
    return this;
  }

   /**
   * Get tenantBotJid
   * @return tenantBotJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantBotJid() {
    return tenantBotJid;
  }

  public void setTenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
  }

  public TenantTbotResponseV5 botPassword(String botPassword) {
    this.botPassword = botPassword;
    return this;
  }

   /**
   * Get botPassword
   * @return botPassword
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBotPassword() {
    return botPassword;
  }

  public void setBotPassword(String botPassword) {
    this.botPassword = botPassword;
  }

  public TenantTbotResponseV5 csBotName(String csBotName) {
    this.csBotName = csBotName;
    return this;
  }

   /**
   * Get csBotName
   * @return csBotName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCsBotName() {
    return csBotName;
  }

  public void setCsBotName(String csBotName) {
    this.csBotName = csBotName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TenantTbotResponseV5 tenantTbotResponseV5 = (TenantTbotResponseV5) o;
    return Objects.equals(this.tenantBotJid, tenantTbotResponseV5.tenantBotJid) &&
        Objects.equals(this.botPassword, tenantTbotResponseV5.botPassword) &&
        Objects.equals(this.csBotName, tenantTbotResponseV5.csBotName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantBotJid, botPassword, csBotName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantTbotResponseV5 {\n");
    
    sb.append("    tenantBotJid: ").append(toIndentedString(tenantBotJid)).append("\n");
    sb.append("    botPassword: ").append(toIndentedString(botPassword)).append("\n");
    sb.append("    csBotName: ").append(toIndentedString(csBotName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

