/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

public class TenantBusinessHoursResponseV5 {
  @SerializedName("businessHours")
  private List<BusinessHourResponse> businessHours = new ArrayList<BusinessHourResponse>();

  public TenantBusinessHoursResponseV5 businessHours(List<BusinessHourResponse> businessHours) {
    this.businessHours = businessHours;
    return this;
  }

  public TenantBusinessHoursResponseV5 addBusinessHoursItem(BusinessHourResponse businessHoursItem) {
    this.businessHours.add(businessHoursItem);
    return this;
  }

   /**
   * Get businessHours
   * @return businessHours
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<BusinessHourResponse> getBusinessHours() {
    return businessHours;
  }

  public void setBusinessHours(List<BusinessHourResponse> businessHours) {
    this.businessHours = businessHours;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TenantBusinessHoursResponseV5 tenantBusinessHoursResponseV5 = (TenantBusinessHoursResponseV5) o;
    return Objects.equals(this.businessHours, tenantBusinessHoursResponseV5.businessHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantBusinessHoursResponseV5 {\n");
    
    sb.append("    businessHours: ").append(toIndentedString(businessHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

