/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, VersionFlow 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * TenantUpdateDto
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-09-06T15:43:34.475Z")
public class TenantUpdateDto extends Tenant{

  public TenantUpdateDto() {
  }

  public TenantUpdateDto(String id, String tenantOrgName, String contactEmail, StateEnum state, String description,
                         String shortDescription, String tenantJid, String tenantBotJid,
                         String category, List<String> tenantTags, Integer sessionsCapacity, List<AddressResponse> tenantAddresses) {
    this.id = id;
    this.tenantOrgName = tenantOrgName;
    this.contactEmail = contactEmail;
    this.state = state;
    this.description = description;
    this.shortDescription = shortDescription;
    this.tenantJid = tenantJid;
    this.tenantBotJid = tenantBotJid;
    this.category = category;
    this.tenantTags = tenantTags;
    this.sessionsCapacity = sessionsCapacity;
    this.tenantAddresses = tenantAddresses;
  }

  @SerializedName("id")
  private String id = null;


  @SerializedName("tenantAddresses")
  private List<AddressResponse> tenantAddresses = new ArrayList<AddressResponse>();

  public TenantUpdateDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TenantUpdateDto tenantOrgName(String tenantOrgName) {
    this.tenantOrgName = tenantOrgName;
    return this;
  }

   /**
   * Get tenantOrgName
   * @return tenantOrgName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantOrgName() {
    return tenantOrgName;
  }

  public void setTenantOrgName(String tenantOrgName) {
    this.tenantOrgName = tenantOrgName;
  }

  public TenantUpdateDto contactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

   /**
   * Get contactEmail
   * @return contactEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(String contactEmail) {
    this.contactEmail = contactEmail;
  }

  public TenantUpdateDto state(StateEnum state) {
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @ApiModelProperty(example = "null", value = "")
  public StateEnum getState() {
    return state;
  }

  public void setState(StateEnum state) {
    this.state = state;
  }

  public TenantUpdateDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TenantUpdateDto shortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
    return this;
  }

   /**
   * Get shortDescription
   * @return shortDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getShortDescription() {
    return shortDescription;
  }

  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  public TenantUpdateDto tenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
    return this;
  }

   /**
   * Get tenantJid
   * @return tenantJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantJid() {
    return tenantJid;
  }

  public void setTenantJid(String tenantJid) {
    this.tenantJid = tenantJid;
  }

  public TenantUpdateDto tenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
    return this;
  }

   /**
   * Get tenantBotJid
   * @return tenantBotJid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTenantBotJid() {
    return tenantBotJid;
  }

  public void setTenantBotJid(String tenantBotJid) {
    this.tenantBotJid = tenantBotJid;
  }

  public TenantUpdateDto category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public TenantUpdateDto tenantTags(List<String> tenantTags) {
    this.tenantTags = tenantTags;
    return this;
  }

  public TenantUpdateDto addTenantTagsItem(String tenantTagsItem) {
    this.tenantTags.add(tenantTagsItem);
    return this;
  }

   /**
   * Get tenantTags
   * @return tenantTags
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<String> getTenantTags() {
    return tenantTags;
  }

  public void setTenantTags(List<String> tenantTags) {
    this.tenantTags = tenantTags;
  }

  public TenantUpdateDto sessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
    return this;
  }

   /**
   * Get sessionsCapacity
   * @return sessionsCapacity
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSessionsCapacity() {
    return sessionsCapacity;
  }

  public void setSessionsCapacity(Integer sessionsCapacity) {
    this.sessionsCapacity = sessionsCapacity;
  }

  public TenantUpdateDto tenantAddresses(List<AddressResponse> tenantAddresses) {
    this.tenantAddresses = tenantAddresses;
    return this;
  }

  public TenantUpdateDto addTenantAddressesItem(AddressResponse tenantAddressesItem) {
    this.tenantAddresses.add(tenantAddressesItem);
    return this;
  }

   /**
   * Get tenantAddresses
   * @return tenantAddresses
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<AddressResponse> getTenantAddresses() {
    return tenantAddresses;
  }

  public void setTenantAddresses(List<AddressResponse> tenantAddresses) {
    this.tenantAddresses = tenantAddresses;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || (getClass() != o.getClass() && TenantRequest.class != o.getClass() && TenantResponse.class != o.getClass())) {
      return false;
    }
    Tenant tenantUpdate = (Tenant) o;
    return Objects.equals(this.tenantOrgName, tenantUpdate.tenantOrgName) &&
            Objects.equals(this.contactEmail, tenantUpdate.contactEmail) &&
            Objects.equals(this.state, tenantUpdate.state) &&
            Objects.equals(this.description, tenantUpdate.description) &&
            Objects.equals(this.shortDescription, tenantUpdate.shortDescription) &&
            Objects.equals(this.tenantJid, tenantUpdate.tenantJid) &&
            Objects.equals(this.tenantBotJid, tenantUpdate.tenantBotJid) &&
            Objects.equals(this.category, tenantUpdate.category) &&
            Objects.equals(this.tenantTags, tenantUpdate.tenantTags) &&
            Objects.equals(this.sessionsCapacity, tenantUpdate.sessionsCapacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, tenantOrgName, contactEmail, state, description, shortDescription, tenantJid, tenantBotJid, category, tenantTags, sessionsCapacity, tenantAddresses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantUpdateDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    tenantOrgName: ").append(toIndentedString(tenantOrgName)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
    sb.append("    tenantJid: ").append(toIndentedString(tenantJid)).append("\n");
    sb.append("    tenantBotJid: ").append(toIndentedString(tenantBotJid)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    tenantTags: ").append(toIndentedString(tenantTags)).append("\n");
    sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
    sb.append("    tenantAddresses: ").append(toIndentedString(tenantAddresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

