/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.tenant;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import com.touch.utils.StringUtils;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * TenantRequestV5
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-06T14:49:12.583Z")
public class TenantRequestV5 {
    @SerializedName("accountId")
    private String accountId = null;

    @SerializedName("tenantOrgName")
    private String tenantOrgName = null;

    @SerializedName("contactEmail")
    private String contactEmail = null;

    /**
     * Gets or Sets state
     */
    public enum StateEnum {
        @SerializedName("ACTIVE")
        ACTIVE("ACTIVE"),

        @SerializedName("INACTIVE")
        INACTIVE("INACTIVE");

        private String value;

        StateEnum(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

    @SerializedName("state")
    private StateEnum state = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("shortDescription")
    private String shortDescription = null;

    @SerializedName("tenantName")
    private String tenantName = null;

    @SerializedName("category")
    private String category = null;

    @SerializedName("tenantTags")
    private List<String> tenantTags = new ArrayList<String>();

    @SerializedName("sessionsCapacity")
    private Integer sessionsCapacity = null;

    @SerializedName("tenantFaqs")
    private List<TenantFaqRequest> tenantFaqs = new ArrayList<TenantFaqRequest>();

    @SerializedName("tenantColours")
    private List<TenantColour> tenantColours = new ArrayList<TenantColour>();

    @SerializedName("tenantAddresses")
    private List<AddressRequest> tenantAddresses = new ArrayList<AddressRequest>();

    @SerializedName("mc2AccountRequest")
    private Mc2AccountRequest mc2AccountRequest = null;

    public TenantRequestV5() {
        this.accountId = "2c9f830756e0e99f0156e13ed4ed003d";
        this.tenantOrgName = StringUtils.generateRandomString(10) + "Test1";
        this.contactEmail = StringUtils.generateRandomString(10) + "@sink.sendgrid.net";
        this.state = StateEnum.ACTIVE;
        this.description = StringUtils.generateRandomString(10);
        this.shortDescription = StringUtils.generateRandomString(10);
        this.tenantName = "Test" + StringUtils.generateRandomString(7);
        this.category = "Banking";
        this.tenantTags = new ArrayList<>();
        this.sessionsCapacity = 5;
        this.tenantAddresses = new ArrayList<>();
        tenantAddresses.add(new AddressRequest());
        this.tenantFaqs = new ArrayList<>();
        this.tenantColours = new ArrayList<>();
        tenantColours.add(new TenantColour());
        this.mc2AccountRequest = new Mc2AccountRequest();
    }

    public TenantRequestV5(String accountId, String tenantOrgName, String contactEmail, StateEnum state, String description, String shortDescription, String tenantName, String category, List<String> tenantTags, Integer sessionsCapacity, List<TenantFaqRequest> tenantFaqs, List<TenantColour> tenantColours, List<AddressRequest> tenantAddresses, Mc2AccountRequest Mc2AccountRequest) {
        this.accountId = accountId;
        this.tenantOrgName = tenantOrgName;
        this.contactEmail = contactEmail;
        this.state = state;
        this.description = description;
        this.shortDescription = shortDescription;
        this.tenantName = tenantName;
        this.category = category;
        this.tenantTags = tenantTags;
        this.sessionsCapacity = sessionsCapacity;
        this.tenantFaqs = tenantFaqs;
        this.tenantColours = tenantColours;
        this.tenantAddresses = tenantAddresses;
        this.mc2AccountRequest = Mc2AccountRequest;
    }

    public TenantRequestV5 accountId(String accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Get accountId
     *
     * @return accountId
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public TenantRequestV5 tenantOrgName(String tenantOrgName) {
        this.tenantOrgName = tenantOrgName;
        return this;
    }

    /**
     * Get tenantOrgName
     *
     * @return tenantOrgName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTenantOrgName() {
        return tenantOrgName;
    }

    public void setTenantOrgName(String tenantOrgName) {
        this.tenantOrgName = tenantOrgName;
    }

    public TenantRequestV5 contactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
        return this;
    }

    /**
     * Get contactEmail
     *
     * @return contactEmail
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public TenantRequestV5 state(StateEnum state) {
        this.state = state;
        return this;
    }

    /**
     * Get state
     *
     * @return state
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public StateEnum getState() {
        return state;
    }

    public void setState(StateEnum state) {
        this.state = state;
    }

    public TenantRequestV5 description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public TenantRequestV5 shortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
        return this;
    }

    /**
     * Get shortDescription
     *
     * @return shortDescription
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getShortDescription() {
        return shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public TenantRequestV5 tenantName(String tenantName) {
        this.tenantName = tenantName;
        return this;
    }

    /**
     * Get tenantName
     *
     * @return tenantName
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getTenantName() {
        return tenantName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    public TenantRequestV5 category(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get category
     *
     * @return category
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public TenantRequestV5 tenantTags(List<String> tenantTags) {
        this.tenantTags = tenantTags;
        return this;
    }

    public TenantRequestV5 addTenantTagsItem(String tenantTagsItem) {
        this.tenantTags.add(tenantTagsItem);
        return this;
    }

    /**
     * Get tenantTags
     *
     * @return tenantTags
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<String> getTenantTags() {
        return tenantTags;
    }

    public void setTenantTags(List<String> tenantTags) {
        this.tenantTags = tenantTags;
    }

    public TenantRequestV5 sessionsCapacity(Integer sessionsCapacity) {
        this.sessionsCapacity = sessionsCapacity;
        return this;
    }

    /**
     * Get sessionsCapacity
     *
     * @return sessionsCapacity
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getSessionsCapacity() {
        return sessionsCapacity;
    }

    public void setSessionsCapacity(Integer sessionsCapacity) {
        this.sessionsCapacity = sessionsCapacity;
    }

    public TenantRequestV5 tenantFaqs(List<TenantFaqRequest> tenantFaqs) {
        this.tenantFaqs = tenantFaqs;
        return this;
    }

    public TenantRequestV5 addTenantFaqsItem(TenantFaqRequest tenantFaqsItem) {
        this.tenantFaqs.add(tenantFaqsItem);
        return this;
    }

    /**
     * Get tenantFaqs
     *
     * @return tenantFaqs
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<TenantFaqRequest> getTenantFaqs() {
        return tenantFaqs;
    }

    public void setTenantFaqs(List<TenantFaqRequest> tenantFaqs) {
        this.tenantFaqs = tenantFaqs;
    }

    public TenantRequestV5 tenantColours(List<TenantColour> tenantColours) {
        this.tenantColours = tenantColours;
        return this;
    }

    public TenantRequestV5 addTenantColoursItem(TenantColour tenantColoursItem) {
        this.tenantColours.add(tenantColoursItem);
        return this;
    }

    /**
     * Get tenantColours
     *
     * @return tenantColours
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<TenantColour> getTenantColours() {
        return tenantColours;
    }

    public void setTenantColours(List<TenantColour> tenantColours) {
        this.tenantColours = tenantColours;
    }

    public TenantRequestV5 tenantAddresses(List<AddressRequest> tenantAddresses) {
        this.tenantAddresses = tenantAddresses;
        return this;
    }

    public TenantRequestV5 addTenantAddressesItem(AddressRequest tenantAddressesItem) {
        this.tenantAddresses.add(tenantAddressesItem);
        return this;
    }

    /**
     * Get tenantAddresses
     *
     * @return tenantAddresses
     **/
    @ApiModelProperty(example = "null", value = "")
    public List<AddressRequest> getTenantAddresses() {
        return tenantAddresses;
    }

    public void setTenantAddresses(List<AddressRequest> tenantAddresses) {
        this.tenantAddresses = tenantAddresses;
    }

    public TenantRequestV5 mc2AccountRequest(Mc2AccountRequest Mc2AccountRequest) {
        this.mc2AccountRequest = Mc2AccountRequest;
        return this;
    }

    /**
     * Get mc2AccountRequest
     *
     * @return mc2AccountRequest
     **/
    @ApiModelProperty(example = "null", required = true, value = "")
    public Mc2AccountRequest getMc2AccountRequest() {
        return mc2AccountRequest;
    }

    public void setMc2AccountRequest(Mc2AccountRequest mc2AccountRequest) {
        this.mc2AccountRequest = mc2AccountRequest;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TenantRequestV5 tenantRequestV5 = (TenantRequestV5) o;
        return Objects.equals(this.accountId, tenantRequestV5.accountId) &&
                Objects.equals(this.tenantOrgName, tenantRequestV5.tenantOrgName) &&
                Objects.equals(this.contactEmail, tenantRequestV5.contactEmail) &&
                Objects.equals(this.state, tenantRequestV5.state) &&
                Objects.equals(this.description, tenantRequestV5.description) &&
                Objects.equals(this.shortDescription, tenantRequestV5.shortDescription) &&
                Objects.equals(this.tenantName, tenantRequestV5.tenantName) &&
                Objects.equals(this.category, tenantRequestV5.category) &&
                Objects.equals(this.tenantTags, tenantRequestV5.tenantTags) &&
                Objects.equals(this.sessionsCapacity, tenantRequestV5.sessionsCapacity) &&
                Objects.equals(this.tenantFaqs, tenantRequestV5.tenantFaqs) &&
                Objects.equals(this.tenantColours, tenantRequestV5.tenantColours) &&
                Objects.equals(this.tenantAddresses, tenantRequestV5.tenantAddresses) &&
                Objects.equals(this.mc2AccountRequest, tenantRequestV5.mc2AccountRequest);
    }

    @Override
    public int hashCode() {
        return Objects.hash(accountId, tenantOrgName, contactEmail, state, description, shortDescription, tenantName, category, tenantTags, sessionsCapacity, tenantFaqs, tenantColours, tenantAddresses, mc2AccountRequest);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TenantRequestV5 {\n");

        sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
        sb.append("    tenantOrgName: ").append(toIndentedString(tenantOrgName)).append("\n");
        sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    shortDescription: ").append(toIndentedString(shortDescription)).append("\n");
        sb.append("    tenantName: ").append(toIndentedString(tenantName)).append("\n");
        sb.append("    category: ").append(toIndentedString(category)).append("\n");
        sb.append("    tenantTags: ").append(toIndentedString(tenantTags)).append("\n");
        sb.append("    sessionsCapacity: ").append(toIndentedString(sessionsCapacity)).append("\n");
        sb.append("    tenantFaqs: ").append(toIndentedString(tenantFaqs)).append("\n");
        sb.append("    tenantColours: ").append(toIndentedString(tenantColours)).append("\n");
        sb.append("    tenantAddresses: ").append(toIndentedString(tenantAddresses)).append("\n");
        sb.append("    mc2AccountRequest: ").append(toIndentedString(mc2AccountRequest)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

