//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.29 at 05:24:47 PM EEST 
//


package com.clickatell.models.mc2.billaccount;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for billingAccountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="billingAccountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dailyBillCycle" type="{http://www.tractbilling.com/billing/1_30/domain}dailyBillCycleType"/>
 *         &lt;element name="person" type="{http://www.tractbilling.com/billing/1_30/domain}personType"/>
 *         &lt;element name="billingAccountCategory" type="{http://www.tractbilling.com/billing/1_30/domain}billingAccountCategoryType"/>
 *         &lt;element name="services" type="{http://www.tractbilling.com/billing/1_30/domain}servicesType"/>
 *         &lt;element name="pendingCharges" type="{http://www.tractbilling.com/billing/1_30/domain}pendingChargesType"/>
 *         &lt;element name="customFieldValues" type="{http://www.tractbilling.com/billing/1_30/domain}customFieldValuesType"/>
 *         &lt;element name="paymentTerm" type="{http://www.tractbilling.com/billing/1_30/domain}paymentTermType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="accountNum" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="automaticRecurringPayment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="balance" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="billType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="currencyType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="eid" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="nextInvoiceDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="pendingChargesTotal" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="queryScope" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="taxExempt" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "billingAccountType", propOrder = {
    "dailyBillCycle",
    "person",
    "billingAccountCategory",
    "services",
    "pendingCharges",
    "customFieldValues",
    "paymentTerm"
})
public class BillingAccountType {

    @XmlElement(required = true)
    protected DailyBillCycleType dailyBillCycle;
    @XmlElement(required = true)
    protected PersonType person;
    @XmlElement(required = true)
    protected BillingAccountCategoryType billingAccountCategory;
    @XmlElement(required = true)
    protected ServicesType services;
    @XmlElement(required = true)
    protected PendingChargesType pendingCharges;
    @XmlElement(required = true)
    protected CustomFieldValuesType customFieldValues;
    @XmlElement(required = true)
    protected PaymentTermType paymentTerm;
    @XmlAttribute(name = "accountNum")
    protected Short accountNum;
    @XmlAttribute(name = "automaticRecurringPayment")
    protected String automaticRecurringPayment;
    @XmlAttribute(name = "balance")
    protected Float balance;
    @XmlAttribute(name = "billType")
    protected String billType;
    @XmlAttribute(name = "currencyType")
    protected String currencyType;
    @XmlAttribute(name = "eid")
    protected Short eid;
    @XmlAttribute(name = "nextInvoiceDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar nextInvoiceDate;
    @XmlAttribute(name = "pendingChargesTotal")
    protected Float pendingChargesTotal;
    @XmlAttribute(name = "queryScope")
    protected String queryScope;
    @XmlAttribute(name = "startDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startDate;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "taxExempt")
    protected String taxExempt;

    /**
     * Gets the value of the dailyBillCycle property.
     * 
     * @return
     *     possible object is
     *     {@link DailyBillCycleType }
     *     
     */
    public DailyBillCycleType getDailyBillCycle() {
        return dailyBillCycle;
    }

    /**
     * Sets the value of the dailyBillCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link DailyBillCycleType }
     *     
     */
    public void setDailyBillCycle(DailyBillCycleType value) {
        this.dailyBillCycle = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link PersonType }
     *     
     */
    public PersonType getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonType }
     *     
     */
    public void setPerson(PersonType value) {
        this.person = value;
    }

    /**
     * Gets the value of the billingAccountCategory property.
     * 
     * @return
     *     possible object is
     *     {@link BillingAccountCategoryType }
     *     
     */
    public BillingAccountCategoryType getBillingAccountCategory() {
        return billingAccountCategory;
    }

    /**
     * Sets the value of the billingAccountCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingAccountCategoryType }
     *     
     */
    public void setBillingAccountCategory(BillingAccountCategoryType value) {
        this.billingAccountCategory = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesType }
     *     
     */
    public ServicesType getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesType }
     *     
     */
    public void setServices(ServicesType value) {
        this.services = value;
    }

    /**
     * Gets the value of the pendingCharges property.
     * 
     * @return
     *     possible object is
     *     {@link PendingChargesType }
     *     
     */
    public PendingChargesType getPendingCharges() {
        return pendingCharges;
    }

    /**
     * Sets the value of the pendingCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link PendingChargesType }
     *     
     */
    public void setPendingCharges(PendingChargesType value) {
        this.pendingCharges = value;
    }

    /**
     * Gets the value of the customFieldValues property.
     * 
     * @return
     *     possible object is
     *     {@link CustomFieldValuesType }
     *     
     */
    public CustomFieldValuesType getCustomFieldValues() {
        return customFieldValues;
    }

    /**
     * Sets the value of the customFieldValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomFieldValuesType }
     *     
     */
    public void setCustomFieldValues(CustomFieldValuesType value) {
        this.customFieldValues = value;
    }

    /**
     * Gets the value of the paymentTerm property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentTermType }
     *     
     */
    public PaymentTermType getPaymentTerm() {
        return paymentTerm;
    }

    /**
     * Sets the value of the paymentTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentTermType }
     *     
     */
    public void setPaymentTerm(PaymentTermType value) {
        this.paymentTerm = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setAccountNum(Short value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the automaticRecurringPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutomaticRecurringPayment() {
        return automaticRecurringPayment;
    }

    /**
     * Sets the value of the automaticRecurringPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomaticRecurringPayment(String value) {
        this.automaticRecurringPayment = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setBalance(Float value) {
        this.balance = value;
    }

    /**
     * Gets the value of the billType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillType() {
        return billType;
    }

    /**
     * Sets the value of the billType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillType(String value) {
        this.billType = value;
    }

    /**
     * Gets the value of the currencyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * Sets the value of the currencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyType(String value) {
        this.currencyType = value;
    }

    /**
     * Gets the value of the eid property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEid() {
        return eid;
    }

    /**
     * Sets the value of the eid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEid(Short value) {
        this.eid = value;
    }

    /**
     * Gets the value of the nextInvoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNextInvoiceDate() {
        return nextInvoiceDate;
    }

    /**
     * Sets the value of the nextInvoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNextInvoiceDate(XMLGregorianCalendar value) {
        this.nextInvoiceDate = value;
    }

    /**
     * Gets the value of the pendingChargesTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getPendingChargesTotal() {
        return pendingChargesTotal;
    }

    /**
     * Sets the value of the pendingChargesTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setPendingChargesTotal(Float value) {
        this.pendingChargesTotal = value;
    }

    /**
     * Gets the value of the queryScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryScope() {
        return queryScope;
    }

    /**
     * Sets the value of the queryScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryScope(String value) {
        this.queryScope = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the taxExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExempt() {
        return taxExempt;
    }

    /**
     * Sets the value of the taxExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExempt(String value) {
        this.taxExempt = value;
    }

}
