//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.29 at 05:24:47 PM EEST 
//


package com.clickatell.models.mc2.billaccount;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the billaccount package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BillingAccount_QNAME = new QName("http://www.tractbilling.com/billing/1_30/domain", "billingAccount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: billaccount
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BillingAccountType }
     * 
     */
    public BillingAccountType createBillingAccountType() {
        return new BillingAccountType();
    }

    /**
     * Create an instance of {@link BillingAccountCategoryType }
     * 
     */
    public BillingAccountCategoryType createBillingAccountCategoryType() {
        return new BillingAccountCategoryType();
    }

    /**
     * Create an instance of {@link DailyBillCycleType }
     * 
     */
    public DailyBillCycleType createDailyBillCycleType() {
        return new DailyBillCycleType();
    }

    /**
     * Create an instance of {@link EmailAddressType }
     * 
     */
    public EmailAddressType createEmailAddressType() {
        return new EmailAddressType();
    }

    /**
     * Create an instance of {@link AddressesType }
     * 
     */
    public AddressesType createAddressesType() {
        return new AddressesType();
    }

    /**
     * Create an instance of {@link PaymentTermType }
     * 
     */
    public PaymentTermType createPaymentTermType() {
        return new PaymentTermType();
    }

    /**
     * Create an instance of {@link TelecomAddressType }
     * 
     */
    public TelecomAddressType createTelecomAddressType() {
        return new TelecomAddressType();
    }

    /**
     * Create an instance of {@link PendingChargesType }
     * 
     */
    public PendingChargesType createPendingChargesType() {
        return new PendingChargesType();
    }

    /**
     * Create an instance of {@link CustomFieldValuesType }
     * 
     */
    public CustomFieldValuesType createCustomFieldValuesType() {
        return new CustomFieldValuesType();
    }

    /**
     * Create an instance of {@link ServicesType }
     * 
     */
    public ServicesType createServicesType() {
        return new ServicesType();
    }

    /**
     * Create an instance of {@link PostalAddressType }
     * 
     */
    public PostalAddressType createPostalAddressType() {
        return new PostalAddressType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillingAccountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tractbilling.com/billing/1_30/domain", name = "billingAccount")
    public JAXBElement<BillingAccountType> createBillingAccount(BillingAccountType value) {
        return new JAXBElement<BillingAccountType>(_BillingAccount_QNAME, BillingAccountType.class, null, value);
    }

}
