//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.29 at 05:24:47 PM EEST 
//


package com.clickatell.models.mc2.billaccount;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for paymentTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paymentTermType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="eid" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="graceDays" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="queryScope" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="termDays" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paymentTermType", propOrder = {
    "value"
})
public class PaymentTermType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "eid")
    protected Byte eid;
    @XmlAttribute(name = "graceDays")
    protected Byte graceDays;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "queryScope")
    protected String queryScope;
    @XmlAttribute(name = "termDays")
    protected Byte termDays;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the eid property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getEid() {
        return eid;
    }

    /**
     * Sets the value of the eid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setEid(Byte value) {
        this.eid = value;
    }

    /**
     * Gets the value of the graceDays property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getGraceDays() {
        return graceDays;
    }

    /**
     * Sets the value of the graceDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setGraceDays(Byte value) {
        this.graceDays = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the queryScope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryScope() {
        return queryScope;
    }

    /**
     * Sets the value of the queryScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryScope(String value) {
        this.queryScope = value;
    }

    /**
     * Gets the value of the termDays property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getTermDays() {
        return termDays;
    }

    /**
     * Sets the value of the termDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setTermDays(Byte value) {
        this.termDays = value;
    }

}
