/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.touch.models.touch.analytics;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;


public class AnalyticsChatSessionsResponse {
  @SerializedName("timeZone")
  private String timeZone = null;

  @SerializedName("totalOpenSessions")
  private Long totalOpenSessions = null;

  @SerializedName("totalClosedSessions")
  private Long totalClosedSessions = null;

  @SerializedName("totalAliveSessions")
  private Long totalAliveSessions = null;

  @SerializedName("averageSessionTime")
  private Long averageSessionTime = null;

  @SerializedName("openedSessionsPerHour")
  private TimeRange openedSessionsPerHour = null;

  public AnalyticsChatSessionsResponse timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public AnalyticsChatSessionsResponse totalOpenSessions(Long totalOpenSessions) {
    this.totalOpenSessions = totalOpenSessions;
    return this;
  }

   /**
   * Get totalOpenSessions
   * @return totalOpenSessions
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalOpenSessions() {
    return totalOpenSessions;
  }

  public void setTotalOpenSessions(Long totalOpenSessions) {
    this.totalOpenSessions = totalOpenSessions;
  }

  public AnalyticsChatSessionsResponse totalClosedSessions(Long totalClosedSessions) {
    this.totalClosedSessions = totalClosedSessions;
    return this;
  }

   /**
   * Get totalClosedSessions
   * @return totalClosedSessions
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalClosedSessions() {
    return totalClosedSessions;
  }

  public void setTotalClosedSessions(Long totalClosedSessions) {
    this.totalClosedSessions = totalClosedSessions;
  }

  public AnalyticsChatSessionsResponse totalAliveSessions(Long totalAliveSessions) {
    this.totalAliveSessions = totalAliveSessions;
    return this;
  }

   /**
   * Get totalAliveSessions
   * @return totalAliveSessions
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalAliveSessions() {
    return totalAliveSessions;
  }

  public void setTotalAliveSessions(Long totalAliveSessions) {
    this.totalAliveSessions = totalAliveSessions;
  }

  public AnalyticsChatSessionsResponse averageSessionTime(Long averageSessionTime) {
    this.averageSessionTime = averageSessionTime;
    return this;
  }

   /**
   * Get averageSessionTime
   * @return averageSessionTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAverageSessionTime() {
    return averageSessionTime;
  }

  public void setAverageSessionTime(Long averageSessionTime) {
    this.averageSessionTime = averageSessionTime;
  }

  public AnalyticsChatSessionsResponse openedSessionsPerHour(TimeRange openedSessionsPerHour) {
    this.openedSessionsPerHour = openedSessionsPerHour;
    return this;
  }

   /**
   * Get openedSessionsPerHour
   * @return openedSessionsPerHour
  **/
  @ApiModelProperty(example = "null", value = "")
  public TimeRange getOpenedSessionsPerHour() {
    return openedSessionsPerHour;
  }

  public void setOpenedSessionsPerHour(TimeRange openedSessionsPerHour) {
    this.openedSessionsPerHour = openedSessionsPerHour;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalyticsChatSessionsResponse analyticsChatSessionsResponse = (AnalyticsChatSessionsResponse) o;
    return Objects.equals(this.timeZone, analyticsChatSessionsResponse.timeZone) &&
        Objects.equals(this.totalOpenSessions, analyticsChatSessionsResponse.totalOpenSessions) &&
        Objects.equals(this.totalClosedSessions, analyticsChatSessionsResponse.totalClosedSessions) &&
        Objects.equals(this.totalAliveSessions, analyticsChatSessionsResponse.totalAliveSessions) &&
        Objects.equals(this.averageSessionTime, analyticsChatSessionsResponse.averageSessionTime) &&
        Objects.equals(this.openedSessionsPerHour, analyticsChatSessionsResponse.openedSessionsPerHour);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timeZone, totalOpenSessions, totalClosedSessions, totalAliveSessions, averageSessionTime, openedSessionsPerHour);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalyticsChatSessionsResponse {\n");
    
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    totalOpenSessions: ").append(toIndentedString(totalOpenSessions)).append("\n");
    sb.append("    totalClosedSessions: ").append(toIndentedString(totalClosedSessions)).append("\n");
    sb.append("    totalAliveSessions: ").append(toIndentedString(totalAliveSessions)).append("\n");
    sb.append("    averageSessionTime: ").append(toIndentedString(averageSessionTime)).append("\n");
    sb.append("    openedSessionsPerHour: ").append(toIndentedString(openedSessionsPerHour)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

