/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.analytics;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

public class ConversationCountStatsResponseV5 {
  @SerializedName("year")
  private String year = null;

  @SerializedName("month")
  private String month = null;

  @SerializedName("day")
  private String day = null;

  @SerializedName("totalConversationCount")
  private Long totalConversationCount = null;

  @SerializedName("agentConversationCount")
  private Long agentConversationCount = null;

  @SerializedName("percentBotConversationCount")
  private Float percentBotConversationCount = null;

  @SerializedName("percentAgentConversationCount")
  private Float percentAgentConversationCount = null;

  public ConversationCountStatsResponseV5 year(String year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getYear() {
    return year;
  }

  public void setYear(String year) {
    this.year = year;
  }

  public ConversationCountStatsResponseV5 month(String month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMonth() {
    return month;
  }

  public void setMonth(String month) {
    this.month = month;
  }

  public ConversationCountStatsResponseV5 day(String day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDay() {
    return day;
  }

  public void setDay(String day) {
    this.day = day;
  }

  public ConversationCountStatsResponseV5 totalConversationCount(Long totalConversationCount) {
    this.totalConversationCount = totalConversationCount;
    return this;
  }

   /**
   * Get totalConversationCount
   * @return totalConversationCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalConversationCount() {
    return totalConversationCount;
  }

  public void setTotalConversationCount(Long totalConversationCount) {
    this.totalConversationCount = totalConversationCount;
  }

  public ConversationCountStatsResponseV5 agentConversationCount(Long agentConversationCount) {
    this.agentConversationCount = agentConversationCount;
    return this;
  }

   /**
   * Get agentConversationCount
   * @return agentConversationCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAgentConversationCount() {
    return agentConversationCount;
  }

  public void setAgentConversationCount(Long agentConversationCount) {
    this.agentConversationCount = agentConversationCount;
  }

  public ConversationCountStatsResponseV5 percentBotConversationCount(Float percentBotConversationCount) {
    this.percentBotConversationCount = percentBotConversationCount;
    return this;
  }

   /**
   * Get percentBotConversationCount
   * @return percentBotConversationCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getPercentBotConversationCount() {
    return percentBotConversationCount;
  }

  public void setPercentBotConversationCount(Float percentBotConversationCount) {
    this.percentBotConversationCount = percentBotConversationCount;
  }

  public ConversationCountStatsResponseV5 percentAgentConversationCount(Float percentAgentConversationCount) {
    this.percentAgentConversationCount = percentAgentConversationCount;
    return this;
  }

   /**
   * Get percentAgentConversationCount
   * @return percentAgentConversationCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getPercentAgentConversationCount() {
    return percentAgentConversationCount;
  }

  public void setPercentAgentConversationCount(Float percentAgentConversationCount) {
    this.percentAgentConversationCount = percentAgentConversationCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationCountStatsResponseV5 conversationCountStatsResponseV5 = (ConversationCountStatsResponseV5) o;
    return Objects.equals(this.year, conversationCountStatsResponseV5.year) &&
        Objects.equals(this.month, conversationCountStatsResponseV5.month) &&
        Objects.equals(this.day, conversationCountStatsResponseV5.day) &&
        Objects.equals(this.totalConversationCount, conversationCountStatsResponseV5.totalConversationCount) &&
        Objects.equals(this.agentConversationCount, conversationCountStatsResponseV5.agentConversationCount) &&
        Objects.equals(this.percentBotConversationCount, conversationCountStatsResponseV5.percentBotConversationCount) &&
        Objects.equals(this.percentAgentConversationCount, conversationCountStatsResponseV5.percentAgentConversationCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, day, totalConversationCount, agentConversationCount, percentBotConversationCount, percentAgentConversationCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationCountStatsResponseV5 {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    totalConversationCount: ").append(toIndentedString(totalConversationCount)).append("\n");
    sb.append("    agentConversationCount: ").append(toIndentedString(agentConversationCount)).append("\n");
    sb.append("    percentBotConversationCount: ").append(toIndentedString(percentBotConversationCount)).append("\n");
    sb.append("    percentAgentConversationCount: ").append(toIndentedString(percentAgentConversationCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

