/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.touch.models.touch.analytics;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

public class ConversationTimeStatsResponseV5 {
  @SerializedName("year")
  private String year = null;

  @SerializedName("month")
  private String month = null;

  @SerializedName("day")
  private String day = null;

  @SerializedName("totalBotConversationTimeMs")
  private Long totalBotConversationTimeMs = null;

  @SerializedName("totalAgentConversationTimeMs")
  private Long totalAgentConversationTimeMs = null;

  @SerializedName("percentBotConversationTime")
  private Float percentBotConversationTime = null;

  @SerializedName("percentAgentConversationTime")
  private Float percentAgentConversationTime = null;

  @SerializedName("avgBotConversationTimeMs")
  private Long avgBotConversationTimeMs = null;

  @SerializedName("avgAgentConversationTimeMs")
  private Long avgAgentConversationTimeMs = null;

  public ConversationTimeStatsResponseV5 year(String year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getYear() {
    return year;
  }

  public void setYear(String year) {
    this.year = year;
  }

  public ConversationTimeStatsResponseV5 month(String month) {
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMonth() {
    return month;
  }

  public void setMonth(String month) {
    this.month = month;
  }

  public ConversationTimeStatsResponseV5 day(String day) {
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDay() {
    return day;
  }

  public void setDay(String day) {
    this.day = day;
  }

  public ConversationTimeStatsResponseV5 totalBotConversationTimeMs(Long totalBotConversationTimeMs) {
    this.totalBotConversationTimeMs = totalBotConversationTimeMs;
    return this;
  }

   /**
   * Get totalBotConversationTimeMs
   * @return totalBotConversationTimeMs
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalBotConversationTimeMs() {
    return totalBotConversationTimeMs;
  }

  public void setTotalBotConversationTimeMs(Long totalBotConversationTimeMs) {
    this.totalBotConversationTimeMs = totalBotConversationTimeMs;
  }

  public ConversationTimeStatsResponseV5 totalAgentConversationTimeMs(Long totalAgentConversationTimeMs) {
    this.totalAgentConversationTimeMs = totalAgentConversationTimeMs;
    return this;
  }

   /**
   * Get totalAgentConversationTimeMs
   * @return totalAgentConversationTimeMs
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalAgentConversationTimeMs() {
    return totalAgentConversationTimeMs;
  }

  public void setTotalAgentConversationTimeMs(Long totalAgentConversationTimeMs) {
    this.totalAgentConversationTimeMs = totalAgentConversationTimeMs;
  }

  public ConversationTimeStatsResponseV5 percentBotConversationTime(Float percentBotConversationTime) {
    this.percentBotConversationTime = percentBotConversationTime;
    return this;
  }

   /**
   * Get percentBotConversationTime
   * @return percentBotConversationTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getPercentBotConversationTime() {
    return percentBotConversationTime;
  }

  public void setPercentBotConversationTime(Float percentBotConversationTime) {
    this.percentBotConversationTime = percentBotConversationTime;
  }

  public ConversationTimeStatsResponseV5 percentAgentConversationTime(Float percentAgentConversationTime) {
    this.percentAgentConversationTime = percentAgentConversationTime;
    return this;
  }

   /**
   * Get percentAgentConversationTime
   * @return percentAgentConversationTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getPercentAgentConversationTime() {
    return percentAgentConversationTime;
  }

  public void setPercentAgentConversationTime(Float percentAgentConversationTime) {
    this.percentAgentConversationTime = percentAgentConversationTime;
  }

  public ConversationTimeStatsResponseV5 avgBotConversationTimeMs(Long avgBotConversationTimeMs) {
    this.avgBotConversationTimeMs = avgBotConversationTimeMs;
    return this;
  }

   /**
   * Get avgBotConversationTimeMs
   * @return avgBotConversationTimeMs
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAvgBotConversationTimeMs() {
    return avgBotConversationTimeMs;
  }

  public void setAvgBotConversationTimeMs(Long avgBotConversationTimeMs) {
    this.avgBotConversationTimeMs = avgBotConversationTimeMs;
  }

  public ConversationTimeStatsResponseV5 avgAgentConversationTimeMs(Long avgAgentConversationTimeMs) {
    this.avgAgentConversationTimeMs = avgAgentConversationTimeMs;
    return this;
  }

   /**
   * Get avgAgentConversationTimeMs
   * @return avgAgentConversationTimeMs
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAvgAgentConversationTimeMs() {
    return avgAgentConversationTimeMs;
  }

  public void setAvgAgentConversationTimeMs(Long avgAgentConversationTimeMs) {
    this.avgAgentConversationTimeMs = avgAgentConversationTimeMs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConversationTimeStatsResponseV5 conversationTimeStatsResponseV5 = (ConversationTimeStatsResponseV5) o;
    return Objects.equals(this.year, conversationTimeStatsResponseV5.year) &&
        Objects.equals(this.month, conversationTimeStatsResponseV5.month) &&
        Objects.equals(this.day, conversationTimeStatsResponseV5.day) &&
        Objects.equals(this.totalBotConversationTimeMs, conversationTimeStatsResponseV5.totalBotConversationTimeMs) &&
        Objects.equals(this.totalAgentConversationTimeMs, conversationTimeStatsResponseV5.totalAgentConversationTimeMs) &&
        Objects.equals(this.percentBotConversationTime, conversationTimeStatsResponseV5.percentBotConversationTime) &&
        Objects.equals(this.percentAgentConversationTime, conversationTimeStatsResponseV5.percentAgentConversationTime) &&
        Objects.equals(this.avgBotConversationTimeMs, conversationTimeStatsResponseV5.avgBotConversationTimeMs) &&
        Objects.equals(this.avgAgentConversationTimeMs, conversationTimeStatsResponseV5.avgAgentConversationTimeMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, day, totalBotConversationTimeMs, totalAgentConversationTimeMs, percentBotConversationTime, percentAgentConversationTime, avgBotConversationTimeMs, avgAgentConversationTimeMs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConversationTimeStatsResponseV5 {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    totalBotConversationTimeMs: ").append(toIndentedString(totalBotConversationTimeMs)).append("\n");
    sb.append("    totalAgentConversationTimeMs: ").append(toIndentedString(totalAgentConversationTimeMs)).append("\n");
    sb.append("    percentBotConversationTime: ").append(toIndentedString(percentBotConversationTime)).append("\n");
    sb.append("    percentAgentConversationTime: ").append(toIndentedString(percentAgentConversationTime)).append("\n");
    sb.append("    avgBotConversationTimeMs: ").append(toIndentedString(avgBotConversationTimeMs)).append("\n");
    sb.append("    avgAgentConversationTimeMs: ").append(toIndentedString(avgAgentConversationTimeMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

