/**
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.mc2.common_data.response.countries;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * CountryShortResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T14:40:21.649Z")
public class CountryShortResponse {
    @SerializedName("id")
    private Integer id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("isoCode3")
    private String isoCode3 = null;

    @SerializedName("isoCode2")
    private String isoCode2 = null;

    public CountryShortResponse id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(example = "null", value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CountryShortResponse name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public CountryShortResponse isoCode3(String isoCode3) {
        this.isoCode3 = isoCode3;
        return this;
    }

    /**
     * Get isoCode3
     *
     * @return isoCode3
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getIsoCode3() {
        return isoCode3;
    }

    public void setIsoCode3(String isoCode3) {
        this.isoCode3 = isoCode3;
    }

    public CountryShortResponse isoCode2(String isoCode2) {
        this.isoCode2 = isoCode2;
        return this;
    }

    /**
     * Get isoCode2
     *
     * @return isoCode2
     **/
    @ApiModelProperty(example = "null", value = "")
    public String getIsoCode2() {
        return isoCode2;
    }

    public void setIsoCode2(String isoCode2) {
        this.isoCode2 = isoCode2;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CountryShortResponse countryShortResponse = (CountryShortResponse) o;
        return Objects.equals(this.id, countryShortResponse.id) &&
                Objects.equals(this.name, countryShortResponse.name) &&
                Objects.equals(this.isoCode3, countryShortResponse.isoCode3) &&
                Objects.equals(this.isoCode2, countryShortResponse.isoCode2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, isoCode3, isoCode2);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CountryShortResponse {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    isoCode3: ").append(toIndentedString(isoCode3)).append("\n");
        sb.append("    isoCode2: ").append(toIndentedString(isoCode2)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

