/**
 * 
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.mc2.accounts.response.account_profile;

import com.clickatell.models.mc2.accounts.request.account_profile.CompanyContactInfoRequest;
import com.clickatell.models.mc2.accounts.request.billing_info.ContactInfoRequest;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * AccountProfileDetailsResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T14:40:21.649Z")
public class AccountProfileDetailsResponse   {
  @SerializedName("companyContact")
  private CompanyContactInfoRequest companyContact = null;

  @SerializedName("companyAddress")
  private AddressInfoResponse companyAddress = null;

  @SerializedName("adminContact")
  private ContactInfoRequest adminContact = null;

  @SerializedName("adminAddress")
  private AddressInfoResponse adminAddress = null;

  @SerializedName("adminAsSupportReused")
  private Boolean adminAsSupportReused = false;

  @SerializedName("supportContact")
  private ContactInfoRequest supportContact = null;

  @SerializedName("adminAsTechReused")
  private Boolean adminAsTechReused = false;

  @SerializedName("techContact")
  private ContactInfoRequest techContact = null;

  public AccountProfileDetailsResponse companyContact(CompanyContactInfoRequest companyContact) {
    this.companyContact = companyContact;
    return this;
  }

   /**
   * Company contact
   * @return companyContact
  **/
  @ApiModelProperty(example = "null", value = "Company contact")
  public CompanyContactInfoRequest getCompanyContact() {
    return companyContact;
  }

  public void setCompanyContact(CompanyContactInfoRequest companyContact) {
    this.companyContact = companyContact;
  }

  public AccountProfileDetailsResponse companyAddress(AddressInfoResponse companyAddress) {
    this.companyAddress = companyAddress;
    return this;
  }

   /**
   * Company address
   * @return companyAddress
  **/
  @ApiModelProperty(example = "null", value = "Company address")
  public AddressInfoResponse getCompanyAddress() {
    return companyAddress;
  }

  public void setCompanyAddress(AddressInfoResponse companyAddress) {
    this.companyAddress = companyAddress;
  }

  public AccountProfileDetailsResponse adminContact(ContactInfoRequest adminContact) {
    this.adminContact = adminContact;
    return this;
  }

   /**
   * Admin contact.
   * @return adminContact
  **/
  @ApiModelProperty(example = "null", value = "Admin contact.")
  public ContactInfoRequest getAdminContact() {
    return adminContact;
  }

  public void setAdminContact(ContactInfoRequest adminContact) {
    this.adminContact = adminContact;
  }

  public AccountProfileDetailsResponse adminAddress(AddressInfoResponse adminAddress) {
    this.adminAddress = adminAddress;
    return this;
  }

   /**
   * Admin address
   * @return adminAddress
  **/
  @ApiModelProperty(example = "null", value = "Admin address")
  public AddressInfoResponse getAdminAddress() {
    return adminAddress;
  }

  public void setAdminAddress(AddressInfoResponse adminAddress) {
    this.adminAddress = adminAddress;
  }

  public AccountProfileDetailsResponse adminAsSupportReused(Boolean adminAsSupportReused) {
    this.adminAsSupportReused = adminAsSupportReused;
    return this;
  }

   /**
   * Define if admin contact may be reused as support; false (disabled) by default.
   * @return adminAsSupportReused
  **/
  @ApiModelProperty(example = "null", value = "Define if admin contact may be reused as support; false (disabled) by default.")
  public Boolean getAdminAsSupportReused() {
    return adminAsSupportReused;
  }

  public void setAdminAsSupportReused(Boolean adminAsSupportReused) {
    this.adminAsSupportReused = adminAsSupportReused;
  }

  public AccountProfileDetailsResponse supportContact(ContactInfoRequest supportContact) {
    this.supportContact = supportContact;
    return this;
  }

   /**
   * Support contact.
   * @return supportContact
  **/
  @ApiModelProperty(example = "null", value = "Support contact.")
  public ContactInfoRequest getSupportContact() {
    return supportContact;
  }

  public void setSupportContact(ContactInfoRequest supportContact) {
    this.supportContact = supportContact;
  }

  public AccountProfileDetailsResponse adminAsTechReused(Boolean adminAsTechReused) {
    this.adminAsTechReused = adminAsTechReused;
    return this;
  }

   /**
   * Define if admin contact may be reused as tech; false (disabled) by default.
   * @return adminAsTechReused
  **/
  @ApiModelProperty(example = "null", value = "Define if admin contact may be reused as tech; false (disabled) by default.")
  public Boolean getAdminAsTechReused() {
    return adminAsTechReused;
  }

  public void setAdminAsTechReused(Boolean adminAsTechReused) {
    this.adminAsTechReused = adminAsTechReused;
  }

  public AccountProfileDetailsResponse techContact(ContactInfoRequest techContact) {
    this.techContact = techContact;
    return this;
  }

   /**
   * Tech contact.
   * @return techContact
  **/
  @ApiModelProperty(example = "null", value = "Tech contact.")
  public ContactInfoRequest getTechContact() {
    return techContact;
  }

  public void setTechContact(ContactInfoRequest techContact) {
    this.techContact = techContact;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountProfileDetailsResponse accountProfileDetailsResponse = (AccountProfileDetailsResponse) o;
    return Objects.equals(this.companyContact, accountProfileDetailsResponse.companyContact) &&
        Objects.equals(this.companyAddress, accountProfileDetailsResponse.companyAddress) &&
        Objects.equals(this.adminContact, accountProfileDetailsResponse.adminContact) &&
        Objects.equals(this.adminAddress, accountProfileDetailsResponse.adminAddress) &&
        Objects.equals(this.adminAsSupportReused, accountProfileDetailsResponse.adminAsSupportReused) &&
        Objects.equals(this.supportContact, accountProfileDetailsResponse.supportContact) &&
        Objects.equals(this.adminAsTechReused, accountProfileDetailsResponse.adminAsTechReused) &&
        Objects.equals(this.techContact, accountProfileDetailsResponse.techContact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyContact, companyAddress, adminContact, adminAddress, adminAsSupportReused, supportContact, adminAsTechReused, techContact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountProfileDetailsResponse {\n");

    sb.append("    companyContact: ").append(toIndentedString(companyContact)).append("\n");
    sb.append("    companyAddress: ").append(toIndentedString(companyAddress)).append("\n");
    sb.append("    adminContact: ").append(toIndentedString(adminContact)).append("\n");
    sb.append("    adminAddress: ").append(toIndentedString(adminAddress)).append("\n");
    sb.append("    adminAsSupportReused: ").append(toIndentedString(adminAsSupportReused)).append("\n");
    sb.append("    supportContact: ").append(toIndentedString(supportContact)).append("\n");
    sb.append("    adminAsTechReused: ").append(toIndentedString(adminAsTechReused)).append("\n");
    sb.append("    techContact: ").append(toIndentedString(techContact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

