/**
 * 
 * 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clickatell.models.mc2.accounts.response.account_profile;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;


/**
 * AccountProfileResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-08T14:40:21.649Z")
public class AccountProfileResponse   {
  @SerializedName("companyName")
  private String companyName = null;

  @SerializedName("profileDetails")
  private AccountProfileDetailsResponse profileDetails = null;

  @SerializedName("accountType")
  private IdNameResponseInteger accountType = null;

  public AccountProfileResponse companyName(String companyName) {
    this.companyName = companyName;
    return this;
  }

   /**
   * Company Name, may be skipped
   * @return companyName
  **/
  @ApiModelProperty(example = "null", value = "Company Name, may be skipped")
  public String getCompanyName() {
    return companyName;
  }

  public void setCompanyName(String companyName) {
    this.companyName = companyName;
  }

  public AccountProfileResponse profileDetails(AccountProfileDetailsResponse profileDetails) {
    this.profileDetails = profileDetails;
    return this;
  }

   /**
   * Profile details: Address and Contact data
   * @return profileDetails
  **/
  @ApiModelProperty(example = "null", value = "Profile details: Address and Contact data")
  public AccountProfileDetailsResponse getProfileDetails() {
    return profileDetails;
  }

  public void setProfileDetails(AccountProfileDetailsResponse profileDetails) {
    this.profileDetails = profileDetails;
  }

  public AccountProfileResponse accountType(IdNameResponseInteger accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Get accountType
   * @return accountType
  **/
  @ApiModelProperty(example = "null", value = "")
  public IdNameResponseInteger getAccountType() {
    return accountType;
  }

  public void setAccountType(IdNameResponseInteger accountType) {
    this.accountType = accountType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountProfileResponse accountProfileResponse = (AccountProfileResponse) o;
    return Objects.equals(this.companyName, accountProfileResponse.companyName) &&
        Objects.equals(this.profileDetails, accountProfileResponse.profileDetails) &&
        Objects.equals(this.accountType, accountProfileResponse.accountType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyName, profileDetails, accountType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountProfileResponse {\n");

    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    profileDetails: ").append(toIndentedString(profileDetails)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

